# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PickColor.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SelectColor(object):
    def setupUi(self, SelectColor):
        SelectColor.setObjectName("SelectColor")
        SelectColor.resize(1070, 451)
        self.gridLayout = QtWidgets.QGridLayout(SelectColor)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.TxtColor = QtWidgets.QTextBrowser(SelectColor)
        self.TxtColor.setMaximumSize(QtCore.QSize(16777215, 100))
        self.TxtColor.setAutoFillBackground(True)
        self.TxtColor.setStyleSheet("background-color: rgb(255, 0, 0)")
        self.TxtColor.setObjectName("TxtColor")
        self.gridLayout.addWidget(self.TxtColor, 1, 2, 2, 2)
        self.LblColorSelected = QtWidgets.QLabel(SelectColor)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LblColorSelected.setFont(font)
        self.LblColorSelected.setObjectName("LblColorSelected")
        self.gridLayout.addWidget(self.LblColorSelected, 0, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(SelectColor)
        self.buttonBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.buttonBox.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 3, 1, 1)
        self.LblColor = QtWidgets.QLabel(SelectColor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LblColor.sizePolicy().hasHeightForWidth())
        self.LblColor.setSizePolicy(sizePolicy)
        self.LblColor.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LblColor.setFont(font)
        self.LblColor.setObjectName("LblColor")
        self.gridLayout.addWidget(self.LblColor, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 4, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(SelectColor)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LblPalette = QtWidgets.QLabel(self.groupBox)
        self.LblPalette.setMaximumSize(QtCore.QSize(1024, 16777215))
        self.LblPalette.setObjectName("LblPalette")
        self.verticalLayout.addWidget(self.LblPalette)
        self.ColorSlider = QtWidgets.QSlider(self.groupBox)
        self.ColorSlider.setMaximum(1530)
        self.ColorSlider.setPageStep(10)
        self.ColorSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ColorSlider.setObjectName("ColorSlider")
        self.verticalLayout.addWidget(self.ColorSlider)
        self.LblSaturation = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LblSaturation.setFont(font)
        self.LblSaturation.setObjectName("LblSaturation")
        self.verticalLayout.addWidget(self.LblSaturation)
        self.BrightnessSlider = QtWidgets.QSlider(self.groupBox)
        self.BrightnessSlider.setMinimum(0)
        self.BrightnessSlider.setMaximum(255)
        self.BrightnessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.BrightnessSlider.setInvertedAppearance(True)
        self.BrightnessSlider.setObjectName("BrightnessSlider")
        self.verticalLayout.addWidget(self.BrightnessSlider)
        self.LblBrightness = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LblBrightness.setFont(font)
        self.LblBrightness.setObjectName("LblBrightness")
        self.verticalLayout.addWidget(self.LblBrightness)
        self.SuturationSlider = QtWidgets.QSlider(self.groupBox)
        self.SuturationSlider.setMinimum(1)
        self.SuturationSlider.setMaximum(100)
        self.SuturationSlider.setProperty("value", 100)
        self.SuturationSlider.setOrientation(QtCore.Qt.Horizontal)
        self.SuturationSlider.setObjectName("SuturationSlider")
        self.verticalLayout.addWidget(self.SuturationSlider)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 5)

        self.retranslateUi(SelectColor)
        QtCore.QMetaObject.connectSlotsByName(SelectColor)

    def retranslateUi(self, SelectColor):
        _translate = QtCore.QCoreApplication.translate
        SelectColor.setWindowTitle(_translate("SelectColor", "Select Color"))
        self.LblColorSelected.setText(_translate("SelectColor", "Selected Color:"))
        self.LblColor.setText(_translate("SelectColor", "255, 0, 0"))
        self.groupBox.setTitle(_translate("SelectColor", "Select Color"))
        self.LblPalette.setText(_translate("SelectColor", "<html><head/><body><p><img src=\":/palette/palette.png\"/><img src=\":/palette/palette.png\"/></p></body></html>"))
        self.LblSaturation.setText(_translate("SelectColor", "Saturation:"))
        self.LblBrightness.setText(_translate("SelectColor", "Brightness: 100%"))

import palette_rc
