# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1084, 647)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.TabAuxLEDs = QtWidgets.QWidget()
        self.TabAuxLEDs.setObjectName("TabAuxLEDs")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.TabAuxLEDs)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.HSliderBrightness2 = QtWidgets.QSlider(self.TabAuxLEDs)
        self.HSliderBrightness2.setEnabled(False)
        self.HSliderBrightness2.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness2.setObjectName("HSliderBrightness2")
        self.gridLayout.addWidget(self.HSliderBrightness2, 9, 2, 1, 1)
        self.BtnEdit = QtWidgets.QPushButton(self.TabAuxLEDs)
        self.BtnEdit.setEnabled(False)
        self.BtnEdit.setObjectName("BtnEdit")
        self.gridLayout.addWidget(self.BtnEdit, 14, 7, 1, 1)
        self.TrStructure = QtWidgets.QTreeWidget(self.TabAuxLEDs)
        self.TrStructure.setObjectName("TrStructure")
        self.TrStructure.headerItem().setText(0, "1")
        self.TrStructure.header().setVisible(False)
        self.gridLayout.addWidget(self.TrStructure, 1, 1, 1, 8)
        self.BtnCreate = QtWidgets.QPushButton(self.TabAuxLEDs)
        self.BtnCreate.setEnabled(False)
        self.BtnCreate.setObjectName("BtnCreate")
        self.gridLayout.addWidget(self.BtnCreate, 2, 8, 1, 1)
        self.LBLLed2_2 = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LBLLed2_2.setEnabled(False)
        self.LBLLed2_2.setObjectName("LBLLed2_2")
        self.gridLayout.addWidget(self.LBLLed2_2, 9, 1, 1, 1)
        self.LstEffects = QtWidgets.QListWidget(self.TabAuxLEDs)
        self.LstEffects.setObjectName("LstEffects")
        self.gridLayout.addWidget(self.LstEffects, 1, 0, 1, 1)
        self.LBLLed7_2 = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LBLLed7_2.setEnabled(False)
        self.LBLLed7_2.setObjectName("LBLLed7_2")
        self.gridLayout.addWidget(self.LBLLed7_2, 11, 3, 1, 1)
        self.BtnRepeat = QtWidgets.QPushButton(self.TabAuxLEDs)
        self.BtnRepeat.setEnabled(False)
        self.BtnRepeat.setObjectName("BtnRepeat")
        self.gridLayout.addWidget(self.BtnRepeat, 12, 8, 1, 1)
        self.LBLLed6_2 = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LBLLed6_2.setEnabled(False)
        self.LBLLed6_2.setObjectName("LBLLed6_2")
        self.gridLayout.addWidget(self.LBLLed6_2, 12, 1, 1, 1)
        self.CBLed7 = QtWidgets.QCheckBox(self.TabAuxLEDs)
        self.CBLed7.setEnabled(False)
        self.CBLed7.setObjectName("CBLed7")
        self.gridLayout.addWidget(self.CBLed7, 4, 7, 1, 1)
        self.CBLed8 = QtWidgets.QCheckBox(self.TabAuxLEDs)
        self.CBLed8.setEnabled(False)
        self.CBLed8.setObjectName("CBLed8")
        self.gridLayout.addWidget(self.CBLed8, 5, 7, 1, 1)
        self.CBLed4 = QtWidgets.QCheckBox(self.TabAuxLEDs)
        self.CBLed4.setEnabled(False)
        self.CBLed4.setObjectName("CBLed4")
        self.gridLayout.addWidget(self.CBLed4, 5, 3, 1, 2)
        self.line_5 = QtWidgets.QFrame(self.TabAuxLEDs)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 10, 6, 1, 2)
        self.ComboRepeat = QtWidgets.QComboBox(self.TabAuxLEDs)
        self.ComboRepeat.setEnabled(False)
        self.ComboRepeat.setObjectName("ComboRepeat")
        self.gridLayout.addWidget(self.ComboRepeat, 12, 6, 1, 1)
        self.LblStructure = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LblStructure.setObjectName("LblStructure")
        self.gridLayout.addWidget(self.LblStructure, 0, 0, 1, 1)
        self.BtnAddSequence = QtWidgets.QPushButton(self.TabAuxLEDs)
        self.BtnAddSequence.setEnabled(False)
        self.BtnAddSequence.setObjectName("BtnAddSequence")
        self.gridLayout.addWidget(self.BtnAddSequence, 5, 8, 1, 1)
        self.LBLLed4_2 = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LBLLed4_2.setEnabled(False)
        self.LBLLed4_2.setObjectName("LBLLed4_2")
        self.gridLayout.addWidget(self.LBLLed4_2, 9, 3, 1, 1)
        self.HSliderBrightness4 = QtWidgets.QSlider(self.TabAuxLEDs)
        self.HSliderBrightness4.setEnabled(False)
        self.HSliderBrightness4.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness4.setObjectName("HSliderBrightness4")
        self.gridLayout.addWidget(self.HSliderBrightness4, 9, 4, 1, 1)
        self.LBLLed5_2 = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LBLLed5_2.setEnabled(False)
        self.LBLLed5_2.setObjectName("LBLLed5_2")
        self.gridLayout.addWidget(self.LBLLed5_2, 11, 1, 1, 1)
        self.LBLLed1_2 = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LBLLed1_2.setEnabled(False)
        self.LBLLed1_2.setObjectName("LBLLed1_2")
        self.gridLayout.addWidget(self.LBLLed1_2, 8, 1, 1, 1)
        self.HSliderBrightness1 = QtWidgets.QSlider(self.TabAuxLEDs)
        self.HSliderBrightness1.setEnabled(False)
        self.HSliderBrightness1.setMaximum(100)
        self.HSliderBrightness1.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness1.setObjectName("HSliderBrightness1")
        self.gridLayout.addWidget(self.HSliderBrightness1, 8, 2, 1, 1)
        self.HSliderBrightness8 = QtWidgets.QSlider(self.TabAuxLEDs)
        self.HSliderBrightness8.setEnabled(False)
        self.HSliderBrightness8.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness8.setObjectName("HSliderBrightness8")
        self.gridLayout.addWidget(self.HSliderBrightness8, 12, 4, 1, 1)
        self.HSliderBrightness5 = QtWidgets.QSlider(self.TabAuxLEDs)
        self.HSliderBrightness5.setEnabled(False)
        self.HSliderBrightness5.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness5.setObjectName("HSliderBrightness5")
        self.gridLayout.addWidget(self.HSliderBrightness5, 11, 2, 1, 1)
        self.LblCount = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LblCount.setObjectName("LblCount")
        self.gridLayout.addWidget(self.LblCount, 11, 7, 1, 1)
        self.ComboCount = QtWidgets.QComboBox(self.TabAuxLEDs)
        self.ComboCount.setEnabled(False)
        self.ComboCount.setObjectName("ComboCount")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.gridLayout.addWidget(self.ComboCount, 12, 7, 1, 1)
        self.LblLed = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LblLed.setObjectName("LblLed")
        self.gridLayout.addWidget(self.LblLed, 7, 1, 1, 1)
        self.HSliderBrightness6 = QtWidgets.QSlider(self.TabAuxLEDs)
        self.HSliderBrightness6.setEnabled(False)
        self.HSliderBrightness6.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness6.setObjectName("HSliderBrightness6")
        self.gridLayout.addWidget(self.HSliderBrightness6, 12, 2, 1, 1)
        self.LblName = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LblName.setObjectName("LblName")
        self.gridLayout.addWidget(self.LblName, 2, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.TabAuxLEDs)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 1, 1, 8)
        self.LblLeds = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LblLeds.setObjectName("LblLeds")
        self.gridLayout.addWidget(self.LblLeds, 4, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.TabAuxLEDs)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 6, 1, 1, 8)
        self.CBLed1 = QtWidgets.QCheckBox(self.TabAuxLEDs)
        self.CBLed1.setEnabled(False)
        self.CBLed1.setObjectName("CBLed1")
        self.gridLayout.addWidget(self.CBLed1, 4, 2, 1, 1)
        self.LblRepeat = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LblRepeat.setObjectName("LblRepeat")
        self.gridLayout.addWidget(self.LblRepeat, 11, 6, 1, 1)
        self.CBLed5 = QtWidgets.QCheckBox(self.TabAuxLEDs)
        self.CBLed5.setEnabled(False)
        self.CBLed5.setObjectName("CBLed5")
        self.gridLayout.addWidget(self.CBLed5, 4, 6, 1, 1)
        self.BtnDelete = QtWidgets.QPushButton(self.TabAuxLEDs)
        self.BtnDelete.setEnabled(False)
        self.BtnDelete.setObjectName("BtnDelete")
        self.gridLayout.addWidget(self.BtnDelete, 14, 8, 1, 1)
        self.CBLed2 = QtWidgets.QCheckBox(self.TabAuxLEDs)
        self.CBLed2.setEnabled(False)
        self.CBLed2.setObjectName("CBLed2")
        self.gridLayout.addWidget(self.CBLed2, 5, 2, 1, 1)
        self.CBLed6 = QtWidgets.QCheckBox(self.TabAuxLEDs)
        self.CBLed6.setEnabled(False)
        self.CBLed6.setObjectName("CBLed6")
        self.gridLayout.addWidget(self.CBLed6, 5, 6, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.TabAuxLEDs)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 11, 5, 2, 1)
        self.line_2 = QtWidgets.QFrame(self.TabAuxLEDs)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 13, 1, 1, 8)
        self.LblBrigtness = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LblBrigtness.setObjectName("LblBrigtness")
        self.gridLayout.addWidget(self.LblBrigtness, 7, 2, 1, 1)
        self.LBLLed_2 = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LBLLed_2.setObjectName("LBLLed_2")
        self.gridLayout.addWidget(self.LBLLed_2, 7, 3, 1, 1)
        self.LBLLed3_2 = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LBLLed3_2.setEnabled(False)
        self.LBLLed3_2.setObjectName("LBLLed3_2")
        self.gridLayout.addWidget(self.LBLLed3_2, 8, 3, 1, 1)
        self.TxtName = QtWidgets.QLineEdit(self.TabAuxLEDs)
        self.TxtName.setObjectName("TxtName")
        self.gridLayout.addWidget(self.TxtName, 2, 2, 1, 6)
        self.CBLedsAll = QtWidgets.QCheckBox(self.TabAuxLEDs)
        self.CBLedsAll.setEnabled(False)
        self.CBLedsAll.setObjectName("CBLedsAll")
        self.gridLayout.addWidget(self.CBLedsAll, 5, 1, 1, 1)
        self.LblList = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LblList.setObjectName("LblList")
        self.gridLayout.addWidget(self.LblList, 0, 1, 1, 1)
        self.HSliderBrightness3 = QtWidgets.QSlider(self.TabAuxLEDs)
        self.HSliderBrightness3.setEnabled(False)
        self.HSliderBrightness3.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness3.setObjectName("HSliderBrightness3")
        self.gridLayout.addWidget(self.HSliderBrightness3, 8, 4, 1, 1)
        self.LBLBrightness2 = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LBLBrightness2.setObjectName("LBLBrightness2")
        self.gridLayout.addWidget(self.LBLBrightness2, 7, 4, 1, 1)
        self.HSliderBrightness7 = QtWidgets.QSlider(self.TabAuxLEDs)
        self.HSliderBrightness7.setEnabled(False)
        self.HSliderBrightness7.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness7.setObjectName("HSliderBrightness7")
        self.gridLayout.addWidget(self.HSliderBrightness7, 11, 4, 1, 1)
        self.LBLLed8_2 = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LBLLed8_2.setEnabled(False)
        self.LBLLed8_2.setObjectName("LBLLed8_2")
        self.gridLayout.addWidget(self.LBLLed8_2, 12, 3, 1, 1)
        self.CBLed3 = QtWidgets.QCheckBox(self.TabAuxLEDs)
        self.CBLed3.setEnabled(False)
        self.CBLed3.setObjectName("CBLed3")
        self.gridLayout.addWidget(self.CBLed3, 4, 3, 1, 2)
        self.SpinWait = QtWidgets.QSpinBox(self.TabAuxLEDs)
        self.SpinWait.setEnabled(False)
        self.SpinWait.setMaximum(1000)
        self.SpinWait.setObjectName("SpinWait")
        self.gridLayout.addWidget(self.SpinWait, 9, 6, 1, 1)
        self.SpinSmooth = QtWidgets.QSpinBox(self.TabAuxLEDs)
        self.SpinSmooth.setEnabled(False)
        self.SpinSmooth.setMaximum(100)
        self.SpinSmooth.setObjectName("SpinSmooth")
        self.gridLayout.addWidget(self.SpinSmooth, 9, 7, 1, 1)
        self.BtnAddStep = QtWidgets.QPushButton(self.TabAuxLEDs)
        self.BtnAddStep.setEnabled(False)
        self.BtnAddStep.setObjectName("BtnAddStep")
        self.gridLayout.addWidget(self.BtnAddStep, 9, 8, 1, 1)
        self.LblWait = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LblWait.setObjectName("LblWait")
        self.gridLayout.addWidget(self.LblWait, 8, 6, 1, 1)
        self.LblSmooth = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LblSmooth.setObjectName("LblSmooth")
        self.gridLayout.addWidget(self.LblSmooth, 8, 7, 1, 1)
        self.LBLName = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LBLName.setObjectName("LBLName")
        self.gridLayout.addWidget(self.LBLName, 7, 6, 1, 1)
        self.TxtStepName = QtWidgets.QLineEdit(self.TabAuxLEDs)
        self.TxtStepName.setEnabled(False)
        self.TxtStepName.setObjectName("TxtStepName")
        self.gridLayout.addWidget(self.TxtStepName, 7, 7, 1, 1)
        self.gridLayout.setColumnStretch(1, 10)
        self.gridLayout.setColumnStretch(2, 10)
        self.gridLayout.setColumnStretch(3, 5)
        self.gridLayout.setColumnStretch(4, 5)
        self.gridLayout.setColumnStretch(5, 10)
        self.gridLayout.setColumnStretch(6, 10)
        self.gridLayout.setRowStretch(1, 20)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.TabAuxLEDs, "")
        self.TabCommon = QtWidgets.QWidget()
        self.TabCommon.setObjectName("TabCommon")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.TabCommon)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.BtnSave = QtWidgets.QPushButton(self.TabCommon)
        self.BtnSave.setEnabled(False)
        self.BtnSave.setObjectName("BtnSave")
        self.gridLayout_2.addWidget(self.BtnSave, 35, 11, 1, 1)
        self.CBScrewEnabled = QtWidgets.QCheckBox(self.TabCommon)
        self.CBScrewEnabled.setText("")
        self.CBScrewEnabled.setObjectName("CBScrewEnabled")
        self.gridLayout_2.addWidget(self.CBScrewEnabled, 28, 11, 1, 1)
        self.BtnDefault = QtWidgets.QPushButton(self.TabCommon)
        self.BtnDefault.setEnabled(False)
        self.BtnDefault.setObjectName("BtnDefault")
        self.gridLayout_2.addWidget(self.BtnDefault, 35, 10, 1, 1)
        self.LblScrew = QtWidgets.QLabel(self.TabCommon)
        self.LblScrew.setObjectName("LblScrew")
        self.gridLayout_2.addWidget(self.LblScrew, 27, 10, 1, 1)
        self.SpinClashFlashDuration = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinClashFlashDuration.setMaximum(99999)
        self.SpinClashFlashDuration.setProperty("value", 72)
        self.SpinClashFlashDuration.setObjectName("SpinClashFlashDuration")
        self.gridLayout_2.addWidget(self.SpinClashFlashDuration, 20, 11, 1, 1)
        self.LblScrewEnabled = QtWidgets.QLabel(self.TabCommon)
        self.LblScrewEnabled.setObjectName("LblScrewEnabled")
        self.gridLayout_2.addWidget(self.LblScrewEnabled, 28, 10, 1, 1)
        self.LblScrewLowW = QtWidgets.QLabel(self.TabCommon)
        self.LblScrewLowW.setObjectName("LblScrewLowW")
        self.gridLayout_2.addWidget(self.LblScrewLowW, 31, 10, 1, 1)
        self.LbScrewHighW = QtWidgets.QLabel(self.TabCommon)
        self.LbScrewHighW.setObjectName("LbScrewHighW")
        self.gridLayout_2.addWidget(self.LbScrewHighW, 30, 10, 1, 1)
        self.SpinScrewLowW = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinScrewLowW.setProperty("value", 5)
        self.SpinScrewLowW.setObjectName("SpinScrewLowW")
        self.gridLayout_2.addWidget(self.SpinScrewLowW, 31, 11, 1, 1)
        self.SpinScrewHighW = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinScrewHighW.setMaximum(999)
        self.SpinScrewHighW.setProperty("value", 200)
        self.SpinScrewHighW.setObjectName("SpinScrewHighW")
        self.gridLayout_2.addWidget(self.SpinScrewHighW, 30, 11, 1, 1)
        self.SpinSpinW = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinSpinW.setMinimum(1)
        self.SpinSpinW.setMaximum(100)
        self.SpinSpinW.setProperty("value", 70)
        self.SpinSpinW.setObjectName("SpinSpinW")
        self.gridLayout_2.addWidget(self.SpinSpinW, 31, 5, 1, 1)
        self.SpinCircleW = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinCircleW.setMaximum(100)
        self.SpinCircleW.setProperty("value", 15)
        self.SpinCircleW.setObjectName("SpinCircleW")
        self.gridLayout_2.addWidget(self.SpinCircleW, 32, 3, 1, 1)
        self.LblSpinW = QtWidgets.QLabel(self.TabCommon)
        self.LblSpinW.setObjectName("LblSpinW")
        self.gridLayout_2.addWidget(self.LblSpinW, 31, 4, 1, 1)
        self.LBLSpinCounter = QtWidgets.QLabel(self.TabCommon)
        self.LBLSpinCounter.setObjectName("LBLSpinCounter")
        self.gridLayout_2.addWidget(self.LBLSpinCounter, 30, 4, 1, 1)
        self.LblCircleW = QtWidgets.QLabel(self.TabCommon)
        self.LblCircleW.setObjectName("LblCircleW")
        self.gridLayout_2.addWidget(self.LblCircleW, 32, 2, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.TabCommon)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 23, 2, 1, 12)
        self.LblSpinCircle = QtWidgets.QLabel(self.TabCommon)
        self.LblSpinCircle.setObjectName("LblSpinCircle")
        self.gridLayout_2.addWidget(self.LblSpinCircle, 32, 4, 1, 1)
        self.LblSpinWLow = QtWidgets.QLabel(self.TabCommon)
        self.LblSpinWLow.setObjectName("LblSpinWLow")
        self.gridLayout_2.addWidget(self.LblSpinWLow, 33, 4, 1, 1)
        self.LblSwingWPercent = QtWidgets.QLabel(self.TabCommon)
        self.LblSwingWPercent.setObjectName("LblSwingWPercent")
        self.gridLayout_2.addWidget(self.LblSwingWPercent, 30, 2, 1, 1)
        self.SpinSpinWLow = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinSpinWLow.setMaximum(100)
        self.SpinSpinWLow.setProperty("value", 40)
        self.SpinSpinWLow.setObjectName("SpinSpinWLow")
        self.gridLayout_2.addWidget(self.SpinSpinWLow, 33, 5, 1, 1)
        self.SpinSwingPercent = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinSwingPercent.setMaximum(100)
        self.SpinSwingPercent.setProperty("value", 50)
        self.SpinSwingPercent.setObjectName("SpinSwingPercent")
        self.gridLayout_2.addWidget(self.SpinSwingPercent, 30, 3, 1, 1)
        self.LblGeneral = QtWidgets.QLabel(self.TabCommon)
        self.LblGeneral.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.LblGeneral.setObjectName("LblGeneral")
        self.gridLayout_2.addWidget(self.LblGeneral, 0, 2, 1, 1)
        self.SpinSpinCounter = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinSpinCounter.setMinimum(2)
        self.SpinSpinCounter.setMaximum(10)
        self.SpinSpinCounter.setProperty("value", 4)
        self.SpinSpinCounter.setObjectName("SpinSpinCounter")
        self.gridLayout_2.addWidget(self.SpinSpinCounter, 30, 5, 1, 1)
        self.SpinSpinCircle = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinSpinCircle.setMinimum(100)
        self.SpinSpinCircle.setMaximum(9999)
        self.SpinSpinCircle.setProperty("value", 640)
        self.SpinSpinCircle.setObjectName("SpinSpinCircle")
        self.gridLayout_2.addWidget(self.SpinSpinCircle, 32, 5, 1, 1)
        self.SpinBand = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinBand.setMinimum(1)
        self.SpinBand.setMaximum(8)
        self.SpinBand.setProperty("value", 3)
        self.SpinBand.setObjectName("SpinBand")
        self.gridLayout_2.addWidget(self.SpinBand, 20, 3, 1, 1)
        self.LblBlade = QtWidgets.QLabel(self.TabCommon)
        self.LblBlade.setObjectName("LblBlade")
        self.gridLayout_2.addWidget(self.LblBlade, 11, 2, 1, 1)
        self.SpinPixPerBand = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinPixPerBand.setMinimum(1)
        self.SpinPixPerBand.setMaximum(144)
        self.SpinPixPerBand.setProperty("value", 144)
        self.SpinPixPerBand.setObjectName("SpinPixPerBand")
        self.gridLayout_2.addWidget(self.SpinPixPerBand, 21, 3, 1, 1)
        self.LblBandNumber = QtWidgets.QLabel(self.TabCommon)
        self.LblBandNumber.setObjectName("LblBandNumber")
        self.gridLayout_2.addWidget(self.LblBandNumber, 20, 2, 1, 1)
        self.LblBladeSettings = QtWidgets.QLabel(self.TabCommon)
        self.LblBladeSettings.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LblBladeSettings.setObjectName("LblBladeSettings")
        self.gridLayout_2.addWidget(self.LblBladeSettings, 1, 2, 1, 1)
        self.LblMotion = QtWidgets.QLabel(self.TabCommon)
        self.LblMotion.setObjectName("LblMotion")
        self.gridLayout_2.addWidget(self.LblMotion, 26, 2, 1, 1)
        self.LblSwing = QtWidgets.QLabel(self.TabCommon)
        self.LblSwing.setTextFormat(QtCore.Qt.AutoText)
        self.LblSwing.setObjectName("LblSwing")
        self.gridLayout_2.addWidget(self.LblSwing, 27, 2, 1, 1)
        self.LBLSpinEnabled = QtWidgets.QLabel(self.TabCommon)
        self.LBLSpinEnabled.setObjectName("LBLSpinEnabled")
        self.gridLayout_2.addWidget(self.LBLSpinEnabled, 28, 4, 1, 1)
        self.LblPixPerBand = QtWidgets.QLabel(self.TabCommon)
        self.LblPixPerBand.setObjectName("LblPixPerBand")
        self.gridLayout_2.addWidget(self.LblPixPerBand, 21, 2, 1, 1)
        self.SpinSwingCircle = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinSwingCircle.setMaximum(9999)
        self.SpinSwingCircle.setProperty("value", 600)
        self.SpinSwingCircle.setObjectName("SpinSwingCircle")
        self.gridLayout_2.addWidget(self.SpinSwingCircle, 31, 3, 1, 1)
        self.LblSwingHighW = QtWidgets.QLabel(self.TabCommon)
        self.LblSwingHighW.setObjectName("LblSwingHighW")
        self.gridLayout_2.addWidget(self.LblSwingHighW, 28, 2, 1, 1)
        self.LBLSpin = QtWidgets.QLabel(self.TabCommon)
        self.LBLSpin.setObjectName("LBLSpin")
        self.gridLayout_2.addWidget(self.LBLSpin, 27, 4, 1, 1)
        self.LblSwingCircle = QtWidgets.QLabel(self.TabCommon)
        self.LblSwingCircle.setObjectName("LblSwingCircle")
        self.gridLayout_2.addWidget(self.LblSwingCircle, 31, 2, 1, 1)
        self.DSpinSwingHighW = QtWidgets.QDoubleSpinBox(self.TabCommon)
        self.DSpinSwingHighW.setMaximum(99.99)
        self.DSpinSwingHighW.setProperty("value", 6.0)
        self.DSpinSwingHighW.setObjectName("DSpinSwingHighW")
        self.gridLayout_2.addWidget(self.DSpinSwingHighW, 28, 3, 1, 1)
        self.CBEnabled = QtWidgets.QCheckBox(self.TabCommon)
        self.CBEnabled.setText("")
        self.CBEnabled.setChecked(True)
        self.CBEnabled.setObjectName("CBEnabled")
        self.gridLayout_2.addWidget(self.CBEnabled, 28, 5, 1, 1)
        self.LblBlade2 = QtWidgets.QLabel(self.TabCommon)
        self.LblBlade2.setObjectName("LblBlade2")
        self.gridLayout_2.addWidget(self.LblBlade2, 11, 4, 1, 1)
        self.LblPixPerBand_2 = QtWidgets.QLabel(self.TabCommon)
        self.LblPixPerBand_2.setObjectName("LblPixPerBand_2")
        self.gridLayout_2.addWidget(self.LblPixPerBand_2, 22, 4, 1, 1)
        self.LblVolume = QtWidgets.QLabel(self.TabCommon)
        self.LblVolume.setObjectName("LblVolume")
        self.gridLayout_2.addWidget(self.LblVolume, 1, 6, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.TabCommon)
        self.spinBox_2.setMaximum(144)
        self.spinBox_2.setProperty("value", 12)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_2.addWidget(self.spinBox_2, 22, 5, 1, 1)
        self.QSpinLength = QtWidgets.QSpinBox(self.TabCommon)
        self.QSpinLength.setMaximum(9999)
        self.QSpinLength.setProperty("value", 15)
        self.QSpinLength.setObjectName("QSpinLength")
        self.gridLayout_2.addWidget(self.QSpinLength, 30, 7, 1, 1)
        self.LblBandNumber_2 = QtWidgets.QLabel(self.TabCommon)
        self.LblBandNumber_2.setObjectName("LblBandNumber_2")
        self.gridLayout_2.addWidget(self.LblBandNumber_2, 21, 4, 1, 1)
        self.SpinBandNumber = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinBandNumber.setMinimum(1)
        self.SpinBandNumber.setMaximum(10)
        self.SpinBandNumber.setProperty("value", 1)
        self.SpinBandNumber.setObjectName("SpinBandNumber")
        self.gridLayout_2.addWidget(self.SpinBandNumber, 21, 5, 1, 1)
        self.LblClashHitLevel = QtWidgets.QLabel(self.TabCommon)
        self.LblClashHitLevel.setObjectName("LblClashHitLevel")
        self.gridLayout_2.addWidget(self.LblClashHitLevel, 31, 6, 1, 1)
        self.LblClashLength = QtWidgets.QLabel(self.TabCommon)
        self.LblClashLength.setObjectName("LblClashLength")
        self.gridLayout_2.addWidget(self.LblClashLength, 30, 6, 1, 1)
        self.LblClashHighA = QtWidgets.QLabel(self.TabCommon)
        self.LblClashHighA.setObjectName("LblClashHighA")
        self.gridLayout_2.addWidget(self.LblClashHighA, 28, 6, 1, 1)
        self.SpinClashHitLevel = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinClashHitLevel.setMinimum(-1000)
        self.SpinClashHitLevel.setMaximum(1000)
        self.SpinClashHitLevel.setSingleStep(50)
        self.SpinClashHitLevel.setProperty("value", -200)
        self.SpinClashHitLevel.setObjectName("SpinClashHitLevel")
        self.gridLayout_2.addWidget(self.SpinClashHitLevel, 31, 7, 1, 1)
        self.LblCOarseMid = QtWidgets.QLabel(self.TabCommon)
        self.LblCOarseMid.setObjectName("LblCOarseMid")
        self.gridLayout_2.addWidget(self.LblCOarseMid, 21, 6, 1, 1)
        self.LblCommon = QtWidgets.QLabel(self.TabCommon)
        self.LblCommon.setObjectName("LblCommon")
        self.gridLayout_2.addWidget(self.LblCommon, 11, 6, 1, 1)
        self.LblCoarseHigh = QtWidgets.QLabel(self.TabCommon)
        self.LblCoarseHigh.setObjectName("LblCoarseHigh")
        self.gridLayout_2.addWidget(self.LblCoarseHigh, 22, 6, 1, 1)
        self.LblClash = QtWidgets.QLabel(self.TabCommon)
        self.LblClash.setObjectName("LblClash")
        self.gridLayout_2.addWidget(self.LblClash, 27, 6, 1, 1)
        self.LblCoarceLow = QtWidgets.QLabel(self.TabCommon)
        self.LblCoarceLow.setObjectName("LblCoarceLow")
        self.gridLayout_2.addWidget(self.LblCoarceLow, 20, 6, 1, 1)
        self.LblClashLowW = QtWidgets.QLabel(self.TabCommon)
        self.LblClashLowW.setObjectName("LblClashLowW")
        self.gridLayout_2.addWidget(self.LblClashLowW, 32, 6, 1, 1)
        self.SpinClashHighA = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinClashHighA.setMinimum(1000)
        self.SpinClashHighA.setMaximum(9999)
        self.SpinClashHighA.setProperty("value", 3600)
        self.SpinClashHighA.setObjectName("SpinClashHighA")
        self.gridLayout_2.addWidget(self.SpinClashHighA, 28, 7, 1, 1)
        self.SpinClashLowW = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinClashLowW.setProperty("value", 7)
        self.SpinClashLowW.setObjectName("SpinClashLowW")
        self.gridLayout_2.addWidget(self.SpinClashLowW, 32, 7, 1, 1)
        self.SpinCommon = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinCommon.setMaximum(100)
        self.SpinCommon.setProperty("value", 100)
        self.SpinCommon.setObjectName("SpinCommon")
        self.gridLayout_2.addWidget(self.SpinCommon, 11, 7, 1, 1)
        self.SpinCoarseLow = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinCoarseLow.setMaximum(100)
        self.SpinCoarseLow.setProperty("value", 75)
        self.SpinCoarseLow.setObjectName("SpinCoarseLow")
        self.gridLayout_2.addWidget(self.SpinCoarseLow, 20, 7, 1, 1)
        self.SpinCoarseMid = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinCoarseMid.setMaximum(100)
        self.SpinCoarseMid.setProperty("value", 93)
        self.SpinCoarseMid.setObjectName("SpinCoarseMid")
        self.gridLayout_2.addWidget(self.SpinCoarseMid, 21, 7, 1, 1)
        self.SpinCoarseHigh = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinCoarseHigh.setMaximum(100)
        self.SpinCoarseHigh.setProperty("value", 100)
        self.SpinCoarseHigh.setObjectName("SpinCoarseHigh")
        self.gridLayout_2.addWidget(self.SpinCoarseHigh, 22, 7, 1, 1)
        self.LblStabLowW = QtWidgets.QLabel(self.TabCommon)
        self.LblStabLowW.setObjectName("LblStabLowW")
        self.gridLayout_2.addWidget(self.LblStabLowW, 31, 8, 1, 1)
        self.LblStab = QtWidgets.QLabel(self.TabCommon)
        self.LblStab.setObjectName("LblStab")
        self.gridLayout_2.addWidget(self.LblStab, 27, 8, 1, 1)
        self.LblEnabled = QtWidgets.QLabel(self.TabCommon)
        self.LblEnabled.setObjectName("LblEnabled")
        self.gridLayout_2.addWidget(self.LblEnabled, 28, 8, 1, 1)
        self.LblStabHighA = QtWidgets.QLabel(self.TabCommon)
        self.LblStabHighA.setObjectName("LblStabHighA")
        self.gridLayout_2.addWidget(self.LblStabHighA, 30, 8, 1, 1)
        self.LblStabHitLevel = QtWidgets.QLabel(self.TabCommon)
        self.LblStabHitLevel.setObjectName("LblStabHitLevel")
        self.gridLayout_2.addWidget(self.LblStabHitLevel, 32, 8, 1, 1)
        self.LblSpinLength = QtWidgets.QLabel(self.TabCommon)
        self.LblSpinLength.setObjectName("LblSpinLength")
        self.gridLayout_2.addWidget(self.LblSpinLength, 33, 8, 1, 1)
        self.LblStabPercent = QtWidgets.QLabel(self.TabCommon)
        self.LblStabPercent.setObjectName("LblStabPercent")
        self.gridLayout_2.addWidget(self.LblStabPercent, 34, 8, 1, 1)
        self.CBStabEnabled = QtWidgets.QCheckBox(self.TabCommon)
        self.CBStabEnabled.setText("")
        self.CBStabEnabled.setChecked(True)
        self.CBStabEnabled.setObjectName("CBStabEnabled")
        self.gridLayout_2.addWidget(self.CBStabEnabled, 28, 9, 1, 1)
        self.SpinStabHighA = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinStabHighA.setMaximum(9999)
        self.SpinStabHighA.setSingleStep(10)
        self.SpinStabHighA.setProperty("value", 150)
        self.SpinStabHighA.setObjectName("SpinStabHighA")
        self.gridLayout_2.addWidget(self.SpinStabHighA, 30, 9, 1, 1)
        self.SpinStabLowW = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinStabLowW.setProperty("value", 7)
        self.SpinStabLowW.setObjectName("SpinStabLowW")
        self.gridLayout_2.addWidget(self.SpinStabLowW, 31, 9, 1, 1)
        self.LblPowerOffTimeout = QtWidgets.QLabel(self.TabCommon)
        self.LblPowerOffTimeout.setObjectName("LblPowerOffTimeout")
        self.gridLayout_2.addWidget(self.LblPowerOffTimeout, 11, 10, 1, 1)
        self.SpinStabHitLevel = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinStabHitLevel.setMinimum(-9999)
        self.SpinStabHitLevel.setMaximum(9999)
        self.SpinStabHitLevel.setProperty("value", -200)
        self.SpinStabHitLevel.setObjectName("SpinStabHitLevel")
        self.gridLayout_2.addWidget(self.SpinStabHitLevel, 32, 9, 1, 1)
        self.SpinStabLength = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinStabLength.setProperty("value", 30)
        self.SpinStabLength.setObjectName("SpinStabLength")
        self.gridLayout_2.addWidget(self.SpinStabLength, 33, 9, 1, 1)
        self.SpinStabPercent = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinStabPercent.setMaximum(100)
        self.SpinStabPercent.setProperty("value", 90)
        self.SpinStabPercent.setObjectName("SpinStabPercent")
        self.gridLayout_2.addWidget(self.SpinStabPercent, 34, 9, 1, 1)
        self.LblDeadTimeSettings = QtWidgets.QLabel(self.TabCommon)
        self.LblDeadTimeSettings.setObjectName("LblDeadTimeSettings")
        self.gridLayout_2.addWidget(self.LblDeadTimeSettings, 1, 8, 1, 1)
        self.LblAfterPowerOn = QtWidgets.QLabel(self.TabCommon)
        self.LblAfterPowerOn.setObjectName("LblAfterPowerOn")
        self.gridLayout_2.addWidget(self.LblAfterPowerOn, 11, 8, 1, 1)
        self.LblAfterBlaster = QtWidgets.QLabel(self.TabCommon)
        self.LblAfterBlaster.setObjectName("LblAfterBlaster")
        self.gridLayout_2.addWidget(self.LblAfterBlaster, 20, 8, 1, 1)
        self.LblAfterClash = QtWidgets.QLabel(self.TabCommon)
        self.LblAfterClash.setObjectName("LblAfterClash")
        self.gridLayout_2.addWidget(self.LblAfterClash, 21, 8, 1, 1)
        self.SpinAfterPowerOn = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinAfterPowerOn.setMaximum(99999)
        self.SpinAfterPowerOn.setProperty("value", 500)
        self.SpinAfterPowerOn.setObjectName("SpinAfterPowerOn")
        self.gridLayout_2.addWidget(self.SpinAfterPowerOn, 11, 9, 1, 1)
        self.SpinAfterBlaster = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinAfterBlaster.setMaximum(99999)
        self.SpinAfterBlaster.setProperty("value", 500)
        self.SpinAfterBlaster.setObjectName("SpinAfterBlaster")
        self.gridLayout_2.addWidget(self.SpinAfterBlaster, 20, 9, 1, 1)
        self.SpinAfterClash = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinAfterClash.setMaximum(99999)
        self.SpinAfterClash.setProperty("value", 500)
        self.SpinAfterClash.setObjectName("SpinAfterClash")
        self.gridLayout_2.addWidget(self.SpinAfterClash, 21, 9, 1, 1)
        self.LblClashFlashDuration = QtWidgets.QLabel(self.TabCommon)
        self.LblClashFlashDuration.setObjectName("LblClashFlashDuration")
        self.gridLayout_2.addWidget(self.LblClashFlashDuration, 20, 10, 1, 1)
        self.SpinPowerOffTimeout = QtWidgets.QSpinBox(self.TabCommon)
        self.SpinPowerOffTimeout.setMaximum(99999)
        self.SpinPowerOffTimeout.setProperty("value", 300)
        self.SpinPowerOffTimeout.setObjectName("SpinPowerOffTimeout")
        self.gridLayout_2.addWidget(self.SpinPowerOffTimeout, 11, 11, 1, 1)
        self.CBBlade2Enabled = QtWidgets.QCheckBox(self.TabCommon)
        self.CBBlade2Enabled.setText("")
        self.CBBlade2Enabled.setChecked(True)
        self.CBBlade2Enabled.setObjectName("CBBlade2Enabled")
        self.gridLayout_2.addWidget(self.CBBlade2Enabled, 20, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.TabCommon)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 20, 4, 1, 1)
        self.tabWidget.addTab(self.TabCommon, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1084, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAuxLeds_Editor_Help = QtWidgets.QAction(MainWindow)
        self.actionAuxLeds_Editor_Help.setObjectName("actionAuxLeds_Editor_Help")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAuxLeds_Editor_Help)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SettingsEditor"))
        self.BtnEdit.setText(_translate("MainWindow", "Edit"))
        self.BtnCreate.setText(_translate("MainWindow", "Create Effect"))
        self.LBLLed2_2.setText(_translate("MainWindow", "LED2:"))
        self.LBLLed7_2.setText(_translate("MainWindow", "LED7:"))
        self.BtnRepeat.setText(_translate("MainWindow", "AddRepeat"))
        self.LBLLed6_2.setText(_translate("MainWindow", "LED6:"))
        self.CBLed7.setText(_translate("MainWindow", "LED7"))
        self.CBLed8.setText(_translate("MainWindow", "LED8"))
        self.CBLed4.setText(_translate("MainWindow", "LED4"))
        self.LblStructure.setText(_translate("MainWindow", "Effect List:"))
        self.BtnAddSequence.setText(_translate("MainWindow", "Add Sequencer"))
        self.LBLLed4_2.setText(_translate("MainWindow", "LED4:"))
        self.LBLLed5_2.setText(_translate("MainWindow", "LED5:"))
        self.LBLLed1_2.setText(_translate("MainWindow", "LED1:"))
        self.LblCount.setText(_translate("MainWindow", "Count:"))
        self.ComboCount.setItemText(0, _translate("MainWindow", "forever"))
        self.ComboCount.setItemText(1, _translate("MainWindow", "1"))
        self.ComboCount.setItemText(2, _translate("MainWindow", "2"))
        self.ComboCount.setItemText(3, _translate("MainWindow", "3"))
        self.ComboCount.setItemText(4, _translate("MainWindow", "4"))
        self.ComboCount.setItemText(5, _translate("MainWindow", "5"))
        self.ComboCount.setItemText(6, _translate("MainWindow", "6"))
        self.ComboCount.setItemText(7, _translate("MainWindow", "7"))
        self.ComboCount.setItemText(8, _translate("MainWindow", "8"))
        self.ComboCount.setItemText(9, _translate("MainWindow", "9"))
        self.ComboCount.setItemText(10, _translate("MainWindow", "10"))
        self.LblLed.setText(_translate("MainWindow", "LED:"))
        self.LblName.setText(_translate("MainWindow", "Effect name:"))
        self.LblLeds.setText(_translate("MainWindow", "Leds for Sequencer:"))
        self.CBLed1.setText(_translate("MainWindow", "LED1"))
        self.LblRepeat.setText(_translate("MainWindow", "Repeat:"))
        self.CBLed5.setText(_translate("MainWindow", "LED5"))
        self.BtnDelete.setText(_translate("MainWindow", "Delete"))
        self.CBLed2.setText(_translate("MainWindow", "LED2"))
        self.CBLed6.setText(_translate("MainWindow", "LED6"))
        self.LblBrigtness.setText(_translate("MainWindow", "Led Brightness:"))
        self.LBLLed_2.setText(_translate("MainWindow", "LED:"))
        self.LBLLed3_2.setText(_translate("MainWindow", "LED3:"))
        self.CBLedsAll.setText(_translate("MainWindow", "Check All"))
        self.LblList.setText(_translate("MainWindow", "Effects Structure:"))
        self.LBLBrightness2.setText(_translate("MainWindow", "Led Brightness:"))
        self.LBLLed8_2.setText(_translate("MainWindow", "LED8:"))
        self.CBLed3.setText(_translate("MainWindow", "LED3"))
        self.BtnAddStep.setText(_translate("MainWindow", "Add Step"))
        self.LblWait.setText(_translate("MainWindow", "Wait:"))
        self.LblSmooth.setText(_translate("MainWindow", "Smooth:"))
        self.LBLName.setText(_translate("MainWindow", "Name:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabAuxLEDs), _translate("MainWindow", "AuxLeds"))
        self.BtnSave.setText(_translate("MainWindow", "Save"))
        self.BtnDefault.setText(_translate("MainWindow", "Back to default"))
        self.LblScrew.setText(_translate("MainWindow", "Screw:"))
        self.LblScrewEnabled.setText(_translate("MainWindow", "Enabled:"))
        self.LblScrewLowW.setText(_translate("MainWindow", "LowW:"))
        self.LbScrewHighW.setText(_translate("MainWindow", "HighW:"))
        self.LblSpinW.setText(_translate("MainWindow", "Spin Start W:"))
        self.LBLSpinCounter.setText(_translate("MainWindow", "Counter:"))
        self.LblCircleW.setText(_translate("MainWindow", "Circle W Threshold:"))
        self.LblSpinCircle.setText(_translate("MainWindow", "Circle:"))
        self.LblSpinWLow.setText(_translate("MainWindow", "WLow:"))
        self.LblSwingWPercent.setText(_translate("MainWindow", "WPercent:"))
        self.LblGeneral.setText(_translate("MainWindow", "General Settings"))
        self.LblBlade.setText(_translate("MainWindow", "Blade1:"))
        self.LblBandNumber.setText(_translate("MainWindow", "BandNumber:"))
        self.LblBladeSettings.setText(_translate("MainWindow", "Blade Settings:"))
        self.LblMotion.setText(_translate("MainWindow", "Motion Settings"))
        self.LblSwing.setText(_translate("MainWindow", "Swing:"))
        self.LBLSpinEnabled.setText(_translate("MainWindow", "Enabled:"))
        self.LblPixPerBand.setText(_translate("MainWindow", "PixPerBand:"))
        self.LblSwingHighW.setText(_translate("MainWindow", "High W Threshold:"))
        self.LBLSpin.setText(_translate("MainWindow", "Spin:"))
        self.LblSwingCircle.setText(_translate("MainWindow", "Circle:"))
        self.LblBlade2.setText(_translate("MainWindow", "Blade2"))
        self.LblPixPerBand_2.setText(_translate("MainWindow", "PixPerBand:"))
        self.LblVolume.setText(_translate("MainWindow", "Volume Settings:"))
        self.LblBandNumber_2.setText(_translate("MainWindow", "BandNumber:"))
        self.LblClashHitLevel.setText(_translate("MainWindow", "HitLevel:"))
        self.LblClashLength.setText(_translate("MainWindow", "Length, ms:"))
        self.LblClashHighA.setText(_translate("MainWindow", "HighA:"))
        self.LblCOarseMid.setText(_translate("MainWindow", "CoarseMid, %:"))
        self.LblCommon.setText(_translate("MainWindow", "Common, %:"))
        self.LblCoarseHigh.setText(_translate("MainWindow", "CoarseHigh, %:"))
        self.LblClash.setText(_translate("MainWindow", "Clash:"))
        self.LblCoarceLow.setText(_translate("MainWindow", "CoarseLow, %:"))
        self.LblClashLowW.setText(_translate("MainWindow", "LowW:"))
        self.LblStabLowW.setText(_translate("MainWindow", "LowW:"))
        self.LblStab.setText(_translate("MainWindow", "Stab:"))
        self.LblEnabled.setText(_translate("MainWindow", "Enabled:"))
        self.LblStabHighA.setText(_translate("MainWindow", "HighA:"))
        self.LblStabHitLevel.setText(_translate("MainWindow", "HitLevel:"))
        self.LblSpinLength.setText(_translate("MainWindow", "Length, ms:"))
        self.LblStabPercent.setText(_translate("MainWindow", "Percent:"))
        self.LblPowerOffTimeout.setText(_translate("MainWindow", "PowerOffTimeout, ms:"))
        self.LblDeadTimeSettings.setText(_translate("MainWindow", "DeadTime Settings:"))
        self.LblAfterPowerOn.setText(_translate("MainWindow", "AfterPowerOn, ms:"))
        self.LblAfterBlaster.setText(_translate("MainWindow", "AfterBlaster, ms:"))
        self.LblAfterClash.setText(_translate("MainWindow", "AfterClash, ms:"))
        self.LblClashFlashDuration.setText(_translate("MainWindow", "ClashFlasDuration, ms:"))
        self.label.setText(_translate("MainWindow", "Enabled"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabCommon), _translate("MainWindow", "Common"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAuxLeds_Editor_Help.setText(_translate("MainWindow", "AuxLeds Editor Help..."))
        self.actionAbout.setText(_translate("MainWindow", "About"))

