# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1124, 668)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.TabAuxLEDs = QtWidgets.QWidget()
        self.TabAuxLEDs.setObjectName("TabAuxLEDs")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.TabAuxLEDs)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.HSliderBrightness2 = QtWidgets.QSlider(self.TabAuxLEDs)
        self.HSliderBrightness2.setEnabled(False)
        self.HSliderBrightness2.setMaximum(100)
        self.HSliderBrightness2.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness2.setObjectName("HSliderBrightness2")
        self.gridLayout.addWidget(self.HSliderBrightness2, 9, 2, 1, 1)
        self.BtnEdit = QtWidgets.QPushButton(self.TabAuxLEDs)
        self.BtnEdit.setEnabled(False)
        self.BtnEdit.setObjectName("BtnEdit")
        self.gridLayout.addWidget(self.BtnEdit, 14, 7, 1, 1)
        self.TrStructure = QtWidgets.QTreeWidget(self.TabAuxLEDs)
        self.TrStructure.setObjectName("TrStructure")
        self.TrStructure.headerItem().setText(0, "1")
        self.TrStructure.header().setVisible(False)
        self.gridLayout.addWidget(self.TrStructure, 1, 1, 1, 8)
        self.BtnCreate = QtWidgets.QPushButton(self.TabAuxLEDs)
        self.BtnCreate.setEnabled(False)
        self.BtnCreate.setObjectName("BtnCreate")
        self.gridLayout.addWidget(self.BtnCreate, 2, 8, 1, 1)
        self.LBLLed2_2 = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LBLLed2_2.setEnabled(False)
        self.LBLLed2_2.setObjectName("LBLLed2_2")
        self.gridLayout.addWidget(self.LBLLed2_2, 9, 1, 1, 1)
        self.LstEffects = QtWidgets.QListWidget(self.TabAuxLEDs)
        self.LstEffects.setObjectName("LstEffects")
        self.gridLayout.addWidget(self.LstEffects, 1, 0, 1, 1)
        self.LBLLed7_2 = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LBLLed7_2.setEnabled(False)
        self.LBLLed7_2.setObjectName("LBLLed7_2")
        self.gridLayout.addWidget(self.LBLLed7_2, 11, 3, 1, 1)
        self.BtnRepeat = QtWidgets.QPushButton(self.TabAuxLEDs)
        self.BtnRepeat.setEnabled(False)
        self.BtnRepeat.setObjectName("BtnRepeat")
        self.gridLayout.addWidget(self.BtnRepeat, 12, 8, 1, 1)
        self.LBLLed6_2 = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LBLLed6_2.setEnabled(False)
        self.LBLLed6_2.setObjectName("LBLLed6_2")
        self.gridLayout.addWidget(self.LBLLed6_2, 12, 1, 1, 1)
        self.CBLed7 = QtWidgets.QCheckBox(self.TabAuxLEDs)
        self.CBLed7.setEnabled(False)
        self.CBLed7.setObjectName("CBLed7")
        self.gridLayout.addWidget(self.CBLed7, 4, 7, 1, 1)
        self.CBLed8 = QtWidgets.QCheckBox(self.TabAuxLEDs)
        self.CBLed8.setEnabled(False)
        self.CBLed8.setObjectName("CBLed8")
        self.gridLayout.addWidget(self.CBLed8, 5, 7, 1, 1)
        self.CBLed4 = QtWidgets.QCheckBox(self.TabAuxLEDs)
        self.CBLed4.setEnabled(False)
        self.CBLed4.setObjectName("CBLed4")
        self.gridLayout.addWidget(self.CBLed4, 5, 3, 1, 2)
        self.line_5 = QtWidgets.QFrame(self.TabAuxLEDs)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 10, 6, 1, 2)
        self.ComboRepeat = QtWidgets.QComboBox(self.TabAuxLEDs)
        self.ComboRepeat.setEnabled(False)
        self.ComboRepeat.setObjectName("ComboRepeat")
        self.gridLayout.addWidget(self.ComboRepeat, 12, 6, 1, 1)
        self.LblStructure = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LblStructure.setObjectName("LblStructure")
        self.gridLayout.addWidget(self.LblStructure, 0, 0, 1, 1)
        self.BtnAddSequence = QtWidgets.QPushButton(self.TabAuxLEDs)
        self.BtnAddSequence.setEnabled(False)
        self.BtnAddSequence.setObjectName("BtnAddSequence")
        self.gridLayout.addWidget(self.BtnAddSequence, 5, 8, 1, 1)
        self.LBLLed4_2 = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LBLLed4_2.setEnabled(False)
        self.LBLLed4_2.setObjectName("LBLLed4_2")
        self.gridLayout.addWidget(self.LBLLed4_2, 9, 3, 1, 1)
        self.HSliderBrightness4 = QtWidgets.QSlider(self.TabAuxLEDs)
        self.HSliderBrightness4.setEnabled(False)
        self.HSliderBrightness4.setMaximum(100)
        self.HSliderBrightness4.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness4.setObjectName("HSliderBrightness4")
        self.gridLayout.addWidget(self.HSliderBrightness4, 9, 4, 1, 1)
        self.LBLLed5_2 = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LBLLed5_2.setEnabled(False)
        self.LBLLed5_2.setObjectName("LBLLed5_2")
        self.gridLayout.addWidget(self.LBLLed5_2, 11, 1, 1, 1)
        self.LBLLed1_2 = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LBLLed1_2.setEnabled(False)
        self.LBLLed1_2.setObjectName("LBLLed1_2")
        self.gridLayout.addWidget(self.LBLLed1_2, 8, 1, 1, 1)
        self.HSliderBrightness1 = QtWidgets.QSlider(self.TabAuxLEDs)
        self.HSliderBrightness1.setEnabled(False)
        self.HSliderBrightness1.setMaximum(100)
        self.HSliderBrightness1.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness1.setObjectName("HSliderBrightness1")
        self.gridLayout.addWidget(self.HSliderBrightness1, 8, 2, 1, 1)
        self.HSliderBrightness8 = QtWidgets.QSlider(self.TabAuxLEDs)
        self.HSliderBrightness8.setEnabled(False)
        self.HSliderBrightness8.setMaximum(100)
        self.HSliderBrightness8.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness8.setObjectName("HSliderBrightness8")
        self.gridLayout.addWidget(self.HSliderBrightness8, 12, 4, 1, 1)
        self.HSliderBrightness5 = QtWidgets.QSlider(self.TabAuxLEDs)
        self.HSliderBrightness5.setEnabled(False)
        self.HSliderBrightness5.setMaximum(100)
        self.HSliderBrightness5.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness5.setObjectName("HSliderBrightness5")
        self.gridLayout.addWidget(self.HSliderBrightness5, 11, 2, 1, 1)
        self.LblCount = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LblCount.setObjectName("LblCount")
        self.gridLayout.addWidget(self.LblCount, 11, 7, 1, 1)
        self.ComboCount = QtWidgets.QComboBox(self.TabAuxLEDs)
        self.ComboCount.setEnabled(False)
        self.ComboCount.setObjectName("ComboCount")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.gridLayout.addWidget(self.ComboCount, 12, 7, 1, 1)
        self.LblLed = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LblLed.setObjectName("LblLed")
        self.gridLayout.addWidget(self.LblLed, 7, 1, 1, 1)
        self.HSliderBrightness6 = QtWidgets.QSlider(self.TabAuxLEDs)
        self.HSliderBrightness6.setEnabled(False)
        self.HSliderBrightness6.setMaximum(100)
        self.HSliderBrightness6.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness6.setObjectName("HSliderBrightness6")
        self.gridLayout.addWidget(self.HSliderBrightness6, 12, 2, 1, 1)
        self.LblName = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LblName.setObjectName("LblName")
        self.gridLayout.addWidget(self.LblName, 2, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.TabAuxLEDs)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 1, 1, 8)
        self.LblLeds = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LblLeds.setObjectName("LblLeds")
        self.gridLayout.addWidget(self.LblLeds, 4, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.TabAuxLEDs)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 6, 1, 1, 8)
        self.CBLed1 = QtWidgets.QCheckBox(self.TabAuxLEDs)
        self.CBLed1.setEnabled(False)
        self.CBLed1.setObjectName("CBLed1")
        self.gridLayout.addWidget(self.CBLed1, 4, 2, 1, 1)
        self.LblRepeat = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LblRepeat.setObjectName("LblRepeat")
        self.gridLayout.addWidget(self.LblRepeat, 11, 6, 1, 1)
        self.CBLed5 = QtWidgets.QCheckBox(self.TabAuxLEDs)
        self.CBLed5.setEnabled(False)
        self.CBLed5.setObjectName("CBLed5")
        self.gridLayout.addWidget(self.CBLed5, 4, 6, 1, 1)
        self.BtnDelete = QtWidgets.QPushButton(self.TabAuxLEDs)
        self.BtnDelete.setEnabled(False)
        self.BtnDelete.setObjectName("BtnDelete")
        self.gridLayout.addWidget(self.BtnDelete, 14, 8, 1, 1)
        self.CBLed2 = QtWidgets.QCheckBox(self.TabAuxLEDs)
        self.CBLed2.setEnabled(False)
        self.CBLed2.setObjectName("CBLed2")
        self.gridLayout.addWidget(self.CBLed2, 5, 2, 1, 1)
        self.CBLed6 = QtWidgets.QCheckBox(self.TabAuxLEDs)
        self.CBLed6.setEnabled(False)
        self.CBLed6.setObjectName("CBLed6")
        self.gridLayout.addWidget(self.CBLed6, 5, 6, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.TabAuxLEDs)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 11, 5, 2, 1)
        self.line_2 = QtWidgets.QFrame(self.TabAuxLEDs)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 13, 1, 1, 8)
        self.LblBrigtness = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LblBrigtness.setObjectName("LblBrigtness")
        self.gridLayout.addWidget(self.LblBrigtness, 7, 2, 1, 1)
        self.LBLLed_2 = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LBLLed_2.setObjectName("LBLLed_2")
        self.gridLayout.addWidget(self.LBLLed_2, 7, 3, 1, 1)
        self.LBLLed3_2 = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LBLLed3_2.setEnabled(False)
        self.LBLLed3_2.setObjectName("LBLLed3_2")
        self.gridLayout.addWidget(self.LBLLed3_2, 8, 3, 1, 1)
        self.TxtName = QtWidgets.QLineEdit(self.TabAuxLEDs)
        self.TxtName.setObjectName("TxtName")
        self.gridLayout.addWidget(self.TxtName, 2, 2, 1, 6)
        self.CBLedsAll = QtWidgets.QCheckBox(self.TabAuxLEDs)
        self.CBLedsAll.setEnabled(False)
        self.CBLedsAll.setObjectName("CBLedsAll")
        self.gridLayout.addWidget(self.CBLedsAll, 5, 1, 1, 1)
        self.LblList = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LblList.setObjectName("LblList")
        self.gridLayout.addWidget(self.LblList, 0, 1, 1, 1)
        self.HSliderBrightness3 = QtWidgets.QSlider(self.TabAuxLEDs)
        self.HSliderBrightness3.setEnabled(False)
        self.HSliderBrightness3.setMaximum(100)
        self.HSliderBrightness3.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness3.setObjectName("HSliderBrightness3")
        self.gridLayout.addWidget(self.HSliderBrightness3, 8, 4, 1, 1)
        self.LBLBrightness2 = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LBLBrightness2.setObjectName("LBLBrightness2")
        self.gridLayout.addWidget(self.LBLBrightness2, 7, 4, 1, 1)
        self.HSliderBrightness7 = QtWidgets.QSlider(self.TabAuxLEDs)
        self.HSliderBrightness7.setEnabled(False)
        self.HSliderBrightness7.setMaximum(100)
        self.HSliderBrightness7.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness7.setObjectName("HSliderBrightness7")
        self.gridLayout.addWidget(self.HSliderBrightness7, 11, 4, 1, 1)
        self.LBLLed8_2 = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LBLLed8_2.setEnabled(False)
        self.LBLLed8_2.setObjectName("LBLLed8_2")
        self.gridLayout.addWidget(self.LBLLed8_2, 12, 3, 1, 1)
        self.CBLed3 = QtWidgets.QCheckBox(self.TabAuxLEDs)
        self.CBLed3.setEnabled(False)
        self.CBLed3.setObjectName("CBLed3")
        self.gridLayout.addWidget(self.CBLed3, 4, 3, 1, 2)
        self.SpinWait = QtWidgets.QSpinBox(self.TabAuxLEDs)
        self.SpinWait.setEnabled(False)
        self.SpinWait.setMaximum(1000)
        self.SpinWait.setObjectName("SpinWait")
        self.gridLayout.addWidget(self.SpinWait, 9, 6, 1, 1)
        self.SpinSmooth = QtWidgets.QSpinBox(self.TabAuxLEDs)
        self.SpinSmooth.setEnabled(False)
        self.SpinSmooth.setMaximum(9999)
        self.SpinSmooth.setObjectName("SpinSmooth")
        self.gridLayout.addWidget(self.SpinSmooth, 9, 7, 1, 1)
        self.BtnAddStep = QtWidgets.QPushButton(self.TabAuxLEDs)
        self.BtnAddStep.setEnabled(False)
        self.BtnAddStep.setObjectName("BtnAddStep")
        self.gridLayout.addWidget(self.BtnAddStep, 9, 8, 1, 1)
        self.LblWait = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LblWait.setObjectName("LblWait")
        self.gridLayout.addWidget(self.LblWait, 8, 6, 1, 1)
        self.LblSmooth = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LblSmooth.setObjectName("LblSmooth")
        self.gridLayout.addWidget(self.LblSmooth, 8, 7, 1, 1)
        self.LBLName = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LBLName.setObjectName("LBLName")
        self.gridLayout.addWidget(self.LBLName, 7, 6, 1, 1)
        self.TxtStepName = QtWidgets.QLineEdit(self.TabAuxLEDs)
        self.TxtStepName.setEnabled(False)
        self.TxtStepName.setObjectName("TxtStepName")
        self.gridLayout.addWidget(self.TxtStepName, 7, 7, 1, 1)
        self.TxtStatus = QtWidgets.QTextBrowser(self.TabAuxLEDs)
        self.TxtStatus.setObjectName("TxtStatus")
        self.gridLayout.addWidget(self.TxtStatus, 3, 0, 11, 1)
        self.LblStatus = QtWidgets.QLabel(self.TabAuxLEDs)
        self.LblStatus.setObjectName("LblStatus")
        self.gridLayout.addWidget(self.LblStatus, 2, 0, 1, 1)
        self.gridLayout.setColumnStretch(1, 10)
        self.gridLayout.setColumnStretch(2, 10)
        self.gridLayout.setColumnStretch(3, 5)
        self.gridLayout.setColumnStretch(4, 5)
        self.gridLayout.setColumnStretch(5, 10)
        self.gridLayout.setColumnStretch(6, 10)
        self.gridLayout.setRowStretch(1, 20)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.TabAuxLEDs, "")
        self.TabCommon = QtWidgets.QWidget()
        self.TabCommon.setObjectName("TabCommon")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.TabCommon)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_6 = QtWidgets.QFrame(self.TabCommon)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 23, 2, 1, 12)
        self.LblGeneral = QtWidgets.QLabel(self.TabCommon)
        self.LblGeneral.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LblGeneral.setObjectName("LblGeneral")
        self.gridLayout_2.addWidget(self.LblGeneral, 0, 2, 1, 1)
        self.LblMotion = QtWidgets.QLabel(self.TabCommon)
        self.LblMotion.setObjectName("LblMotion")
        self.gridLayout_2.addWidget(self.LblMotion, 26, 2, 1, 1)
        self.GBSpin = QtWidgets.QGroupBox(self.TabCommon)
        self.GBSpin.setObjectName("GBSpin")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.GBSpin)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.LBLSpinCounter = QtWidgets.QLabel(self.GBSpin)
        self.LBLSpinCounter.setObjectName("LBLSpinCounter")
        self.gridLayout_18.addWidget(self.LBLSpinCounter, 1, 0, 1, 1)
        self.CBSpinEnabled = QtWidgets.QCheckBox(self.GBSpin)
        self.CBSpinEnabled.setText("")
        self.CBSpinEnabled.setChecked(True)
        self.CBSpinEnabled.setObjectName("CBSpinEnabled")
        self.gridLayout_18.addWidget(self.CBSpinEnabled, 0, 1, 1, 1)
        self.SpinSpinCircle = QtWidgets.QSpinBox(self.GBSpin)
        self.SpinSpinCircle.setMinimum(100)
        self.SpinSpinCircle.setMaximum(9999)
        self.SpinSpinCircle.setSingleStep(50)
        self.SpinSpinCircle.setProperty("value", 640)
        self.SpinSpinCircle.setObjectName("SpinSpinCircle")
        self.gridLayout_18.addWidget(self.SpinSpinCircle, 3, 1, 1, 1)
        self.LblSpinCircle = QtWidgets.QLabel(self.GBSpin)
        self.LblSpinCircle.setObjectName("LblSpinCircle")
        self.gridLayout_18.addWidget(self.LblSpinCircle, 3, 0, 1, 1)
        self.SpinSpinW = QtWidgets.QSpinBox(self.GBSpin)
        self.SpinSpinW.setMinimum(1)
        self.SpinSpinW.setMaximum(100)
        self.SpinSpinW.setProperty("value", 70)
        self.SpinSpinW.setObjectName("SpinSpinW")
        self.gridLayout_18.addWidget(self.SpinSpinW, 2, 1, 1, 1)
        self.SpinSpinCounter = QtWidgets.QSpinBox(self.GBSpin)
        self.SpinSpinCounter.setMinimum(2)
        self.SpinSpinCounter.setMaximum(10)
        self.SpinSpinCounter.setProperty("value", 4)
        self.SpinSpinCounter.setObjectName("SpinSpinCounter")
        self.gridLayout_18.addWidget(self.SpinSpinCounter, 1, 1, 1, 1)
        self.LBLSpinEnabled = QtWidgets.QLabel(self.GBSpin)
        self.LBLSpinEnabled.setObjectName("LBLSpinEnabled")
        self.gridLayout_18.addWidget(self.LBLSpinEnabled, 0, 0, 1, 1)
        self.LblSpinW = QtWidgets.QLabel(self.GBSpin)
        self.LblSpinW.setObjectName("LblSpinW")
        self.gridLayout_18.addWidget(self.LblSpinW, 2, 0, 1, 1)
        self.LblSpinWLow = QtWidgets.QLabel(self.GBSpin)
        self.LblSpinWLow.setObjectName("LblSpinWLow")
        self.gridLayout_18.addWidget(self.LblSpinWLow, 4, 0, 1, 1)
        self.SpinSpinWLow = QtWidgets.QSpinBox(self.GBSpin)
        self.SpinSpinWLow.setMaximum(100)
        self.SpinSpinWLow.setProperty("value", 40)
        self.SpinSpinWLow.setObjectName("SpinSpinWLow")
        self.gridLayout_18.addWidget(self.SpinSpinWLow, 4, 1, 1, 1)
        self.gridLayout_2.addWidget(self.GBSpin, 27, 3, 1, 4)
        self.GBSwing = QtWidgets.QGroupBox(self.TabCommon)
        self.GBSwing.setObjectName("GBSwing")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.GBSwing)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.LblSwingWPercent = QtWidgets.QLabel(self.GBSwing)
        self.LblSwingWPercent.setObjectName("LblSwingWPercent")
        self.gridLayout_17.addWidget(self.LblSwingWPercent, 1, 0, 1, 1)
        self.SpinSwingPercent = QtWidgets.QSpinBox(self.GBSwing)
        self.SpinSwingPercent.setMaximum(100)
        self.SpinSwingPercent.setProperty("value", 50)
        self.SpinSwingPercent.setObjectName("SpinSwingPercent")
        self.gridLayout_17.addWidget(self.SpinSwingPercent, 1, 1, 1, 1)
        self.LblSwingCircle = QtWidgets.QLabel(self.GBSwing)
        self.LblSwingCircle.setObjectName("LblSwingCircle")
        self.gridLayout_17.addWidget(self.LblSwingCircle, 2, 0, 1, 1)
        self.SpinSwingHighW = QtWidgets.QDoubleSpinBox(self.GBSwing)
        self.SpinSwingHighW.setMaximum(99.99)
        self.SpinSwingHighW.setProperty("value", 6.0)
        self.SpinSwingHighW.setObjectName("SpinSwingHighW")
        self.gridLayout_17.addWidget(self.SpinSwingHighW, 0, 1, 1, 1)
        self.SpinSwingCircle = QtWidgets.QSpinBox(self.GBSwing)
        self.SpinSwingCircle.setMaximum(9999)
        self.SpinSwingCircle.setSingleStep(50)
        self.SpinSwingCircle.setProperty("value", 600)
        self.SpinSwingCircle.setObjectName("SpinSwingCircle")
        self.gridLayout_17.addWidget(self.SpinSwingCircle, 2, 1, 1, 1)
        self.LblSwingHighW = QtWidgets.QLabel(self.GBSwing)
        self.LblSwingHighW.setObjectName("LblSwingHighW")
        self.gridLayout_17.addWidget(self.LblSwingHighW, 0, 0, 1, 1)
        self.LblCircleW = QtWidgets.QLabel(self.GBSwing)
        self.LblCircleW.setObjectName("LblCircleW")
        self.gridLayout_17.addWidget(self.LblCircleW, 3, 0, 1, 1)
        self.SpinSwingCircleW = QtWidgets.QSpinBox(self.GBSwing)
        self.SpinSwingCircleW.setMaximum(100)
        self.SpinSwingCircleW.setProperty("value", 15)
        self.SpinSwingCircleW.setObjectName("SpinSwingCircleW")
        self.gridLayout_17.addWidget(self.SpinSwingCircleW, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.GBSwing, 27, 2, 1, 1)
        self.GBStab = QtWidgets.QGroupBox(self.TabCommon)
        self.GBStab.setObjectName("GBStab")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.GBStab)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.SpinStabLowW = QtWidgets.QSpinBox(self.GBStab)
        self.SpinStabLowW.setProperty("value", 7)
        self.SpinStabLowW.setObjectName("SpinStabLowW")
        self.gridLayout_20.addWidget(self.SpinStabLowW, 2, 1, 1, 1)
        self.LblStabHighA = QtWidgets.QLabel(self.GBStab)
        self.LblStabHighA.setObjectName("LblStabHighA")
        self.gridLayout_20.addWidget(self.LblStabHighA, 1, 0, 1, 1)
        self.LblStabLowW = QtWidgets.QLabel(self.GBStab)
        self.LblStabLowW.setObjectName("LblStabLowW")
        self.gridLayout_20.addWidget(self.LblStabLowW, 2, 0, 1, 1)
        self.LblStabHitLevel = QtWidgets.QLabel(self.GBStab)
        self.LblStabHitLevel.setObjectName("LblStabHitLevel")
        self.gridLayout_20.addWidget(self.LblStabHitLevel, 3, 0, 1, 1)
        self.LblSpinLength = QtWidgets.QLabel(self.GBStab)
        self.LblSpinLength.setObjectName("LblSpinLength")
        self.gridLayout_20.addWidget(self.LblSpinLength, 4, 0, 1, 1)
        self.SpinStabHitLevel = QtWidgets.QSpinBox(self.GBStab)
        self.SpinStabHitLevel.setMinimum(-9999)
        self.SpinStabHitLevel.setMaximum(9999)
        self.SpinStabHitLevel.setSingleStep(50)
        self.SpinStabHitLevel.setProperty("value", -200)
        self.SpinStabHitLevel.setObjectName("SpinStabHitLevel")
        self.gridLayout_20.addWidget(self.SpinStabHitLevel, 3, 1, 1, 1)
        self.CBStabEnabled = QtWidgets.QCheckBox(self.GBStab)
        self.CBStabEnabled.setText("")
        self.CBStabEnabled.setChecked(True)
        self.CBStabEnabled.setObjectName("CBStabEnabled")
        self.gridLayout_20.addWidget(self.CBStabEnabled, 0, 1, 1, 1)
        self.SpinStabHighA = QtWidgets.QSpinBox(self.GBStab)
        self.SpinStabHighA.setMaximum(9999)
        self.SpinStabHighA.setSingleStep(50)
        self.SpinStabHighA.setProperty("value", 150)
        self.SpinStabHighA.setObjectName("SpinStabHighA")
        self.gridLayout_20.addWidget(self.SpinStabHighA, 1, 1, 1, 1)
        self.LblEnabled = QtWidgets.QLabel(self.GBStab)
        self.LblEnabled.setObjectName("LblEnabled")
        self.gridLayout_20.addWidget(self.LblEnabled, 0, 0, 1, 1)
        self.LblStabPercent = QtWidgets.QLabel(self.GBStab)
        self.LblStabPercent.setObjectName("LblStabPercent")
        self.gridLayout_20.addWidget(self.LblStabPercent, 5, 0, 1, 1)
        self.SpinStabLength = QtWidgets.QSpinBox(self.GBStab)
        self.SpinStabLength.setProperty("value", 30)
        self.SpinStabLength.setObjectName("SpinStabLength")
        self.gridLayout_20.addWidget(self.SpinStabLength, 4, 1, 1, 1)
        self.SpinStabPercent = QtWidgets.QSpinBox(self.GBStab)
        self.SpinStabPercent.setMaximum(100)
        self.SpinStabPercent.setProperty("value", 90)
        self.SpinStabPercent.setObjectName("SpinStabPercent")
        self.gridLayout_20.addWidget(self.SpinStabPercent, 5, 1, 1, 1)
        self.gridLayout_2.addWidget(self.GBStab, 27, 10, 1, 2)
        self.GBCommonBlade = QtWidgets.QGroupBox(self.TabCommon)
        self.GBCommonBlade.setObjectName("GBCommonBlade")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.GBCommonBlade)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.LBLBlade2 = QtWidgets.QLabel(self.GBCommonBlade)
        self.LBLBlade2.setObjectName("LBLBlade2")
        self.gridLayout_13.addWidget(self.LBLBlade2, 0, 3, 1, 1)
        self.LblBandNumber = QtWidgets.QLabel(self.GBCommonBlade)
        self.LblBandNumber.setObjectName("LblBandNumber")
        self.gridLayout_13.addWidget(self.LblBandNumber, 2, 0, 1, 1)
        self.SpinBandNumber = QtWidgets.QSpinBox(self.GBCommonBlade)
        self.SpinBandNumber.setMinimum(1)
        self.SpinBandNumber.setMaximum(10)
        self.SpinBandNumber.setProperty("value", 1)
        self.SpinBandNumber.setObjectName("SpinBandNumber")
        self.gridLayout_13.addWidget(self.SpinBandNumber, 2, 4, 1, 1)
        self.LBLBlade2Enabled = QtWidgets.QLabel(self.GBCommonBlade)
        self.LBLBlade2Enabled.setObjectName("LBLBlade2Enabled")
        self.gridLayout_13.addWidget(self.LBLBlade2Enabled, 1, 3, 1, 1)
        self.LblBandNumber_2 = QtWidgets.QLabel(self.GBCommonBlade)
        self.LblBandNumber_2.setObjectName("LblBandNumber_2")
        self.gridLayout_13.addWidget(self.LblBandNumber_2, 2, 3, 1, 1)
        self.SpinPixPerBand = QtWidgets.QSpinBox(self.GBCommonBlade)
        self.SpinPixPerBand.setMinimum(1)
        self.SpinPixPerBand.setMaximum(144)
        self.SpinPixPerBand.setProperty("value", 144)
        self.SpinPixPerBand.setObjectName("SpinPixPerBand")
        self.gridLayout_13.addWidget(self.SpinPixPerBand, 3, 1, 1, 1)
        self.CBBlade2Enabled = QtWidgets.QCheckBox(self.GBCommonBlade)
        self.CBBlade2Enabled.setText("")
        self.CBBlade2Enabled.setChecked(True)
        self.CBBlade2Enabled.setObjectName("CBBlade2Enabled")
        self.gridLayout_13.addWidget(self.CBBlade2Enabled, 1, 4, 1, 1)
        self.LblPixPerBand_2 = QtWidgets.QLabel(self.GBCommonBlade)
        self.LblPixPerBand_2.setObjectName("LblPixPerBand_2")
        self.gridLayout_13.addWidget(self.LblPixPerBand_2, 3, 3, 1, 1)
        self.LblPixPerBand = QtWidgets.QLabel(self.GBCommonBlade)
        self.LblPixPerBand.setObjectName("LblPixPerBand")
        self.gridLayout_13.addWidget(self.LblPixPerBand, 3, 0, 1, 1)
        self.SpinPixPerBand2 = QtWidgets.QSpinBox(self.GBCommonBlade)
        self.SpinPixPerBand2.setMaximum(144)
        self.SpinPixPerBand2.setProperty("value", 12)
        self.SpinPixPerBand2.setObjectName("SpinPixPerBand2")
        self.gridLayout_13.addWidget(self.SpinPixPerBand2, 3, 4, 1, 1)
        self.SpinBand = QtWidgets.QSpinBox(self.GBCommonBlade)
        self.SpinBand.setMinimum(1)
        self.SpinBand.setMaximum(8)
        self.SpinBand.setProperty("value", 3)
        self.SpinBand.setObjectName("SpinBand")
        self.gridLayout_13.addWidget(self.SpinBand, 2, 1, 1, 1)
        self.LBLBlade1 = QtWidgets.QLabel(self.GBCommonBlade)
        self.LBLBlade1.setObjectName("LBLBlade1")
        self.gridLayout_13.addWidget(self.LBLBlade1, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem, 2, 2, 1, 1)
        self.gridLayout_13.setColumnStretch(0, 10)
        self.gridLayout_13.setColumnStretch(1, 10)
        self.gridLayout_13.setColumnStretch(3, 10)
        self.gridLayout_13.setColumnStretch(4, 10)
        self.gridLayout_2.addWidget(self.GBCommonBlade, 11, 2, 4, 4)
        self.TxtCommonStatus = QtWidgets.QTextBrowser(self.TabCommon)
        self.TxtCommonStatus.setMaximumSize(QtCore.QSize(16777215, 50))
        self.TxtCommonStatus.setObjectName("TxtCommonStatus")
        self.gridLayout_2.addWidget(self.TxtCommonStatus, 33, 3, 1, 9)
        self.GBScrew = QtWidgets.QGroupBox(self.TabCommon)
        self.GBScrew.setObjectName("GBScrew")
        self.formLayout = QtWidgets.QFormLayout(self.GBScrew)
        self.formLayout.setObjectName("formLayout")
        self.LblScrewEnabled = QtWidgets.QLabel(self.GBScrew)
        self.LblScrewEnabled.setObjectName("LblScrewEnabled")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.LblScrewEnabled)
        self.CBScrewEnabled = QtWidgets.QCheckBox(self.GBScrew)
        self.CBScrewEnabled.setText("")
        self.CBScrewEnabled.setObjectName("CBScrewEnabled")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.CBScrewEnabled)
        self.LbScrewHighW = QtWidgets.QLabel(self.GBScrew)
        self.LbScrewHighW.setObjectName("LbScrewHighW")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.LbScrewHighW)
        self.SpinScrewHighW = QtWidgets.QSpinBox(self.GBScrew)
        self.SpinScrewHighW.setMaximum(999)
        self.SpinScrewHighW.setProperty("value", 200)
        self.SpinScrewHighW.setObjectName("SpinScrewHighW")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.SpinScrewHighW)
        self.LblScrewLowW = QtWidgets.QLabel(self.GBScrew)
        self.LblScrewLowW.setObjectName("LblScrewLowW")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.LblScrewLowW)
        self.SpinScrewLowW = QtWidgets.QSpinBox(self.GBScrew)
        self.SpinScrewLowW.setProperty("value", 5)
        self.SpinScrewLowW.setObjectName("SpinScrewLowW")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.SpinScrewLowW)
        self.gridLayout_2.addWidget(self.GBScrew, 27, 12, 1, 2)
        self.GBCommonDeadTime = QtWidgets.QGroupBox(self.TabCommon)
        self.GBCommonDeadTime.setObjectName("GBCommonDeadTime")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.GBCommonDeadTime)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.SpinAfterBlaster = QtWidgets.QSpinBox(self.GBCommonDeadTime)
        self.SpinAfterBlaster.setMaximum(99999)
        self.SpinAfterBlaster.setSingleStep(50)
        self.SpinAfterBlaster.setProperty("value", 500)
        self.SpinAfterBlaster.setObjectName("SpinAfterBlaster")
        self.gridLayout_15.addWidget(self.SpinAfterBlaster, 1, 1, 1, 1)
        self.SpinAfterPowerOn = QtWidgets.QSpinBox(self.GBCommonDeadTime)
        self.SpinAfterPowerOn.setMaximum(99999)
        self.SpinAfterPowerOn.setSingleStep(50)
        self.SpinAfterPowerOn.setProperty("value", 500)
        self.SpinAfterPowerOn.setObjectName("SpinAfterPowerOn")
        self.gridLayout_15.addWidget(self.SpinAfterPowerOn, 0, 1, 1, 1)
        self.LblAfterPowerOn = QtWidgets.QLabel(self.GBCommonDeadTime)
        self.LblAfterPowerOn.setObjectName("LblAfterPowerOn")
        self.gridLayout_15.addWidget(self.LblAfterPowerOn, 0, 0, 1, 1)
        self.LblAfterBlaster = QtWidgets.QLabel(self.GBCommonDeadTime)
        self.LblAfterBlaster.setObjectName("LblAfterBlaster")
        self.gridLayout_15.addWidget(self.LblAfterBlaster, 1, 0, 1, 1)
        self.LblAfterClash = QtWidgets.QLabel(self.GBCommonDeadTime)
        self.LblAfterClash.setObjectName("LblAfterClash")
        self.gridLayout_15.addWidget(self.LblAfterClash, 2, 0, 1, 1)
        self.SpinAfterClash = QtWidgets.QSpinBox(self.GBCommonDeadTime)
        self.SpinAfterClash.setMaximum(99999)
        self.SpinAfterClash.setSingleStep(50)
        self.SpinAfterClash.setProperty("value", 500)
        self.SpinAfterClash.setObjectName("SpinAfterClash")
        self.gridLayout_15.addWidget(self.SpinAfterClash, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.GBCommonDeadTime, 11, 9, 4, 2)
        self.GBCommonVolume = QtWidgets.QGroupBox(self.TabCommon)
        self.GBCommonVolume.setObjectName("GBCommonVolume")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.GBCommonVolume)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.SpinCoarseLow = QtWidgets.QSpinBox(self.GBCommonVolume)
        self.SpinCoarseLow.setMaximum(100)
        self.SpinCoarseLow.setProperty("value", 75)
        self.SpinCoarseLow.setObjectName("SpinCoarseLow")
        self.gridLayout_14.addWidget(self.SpinCoarseLow, 1, 1, 1, 1)
        self.SpinCommon = QtWidgets.QSpinBox(self.GBCommonVolume)
        self.SpinCommon.setMaximum(100)
        self.SpinCommon.setProperty("value", 100)
        self.SpinCommon.setObjectName("SpinCommon")
        self.gridLayout_14.addWidget(self.SpinCommon, 0, 1, 1, 1)
        self.SpinCoarseMid = QtWidgets.QSpinBox(self.GBCommonVolume)
        self.SpinCoarseMid.setMaximum(100)
        self.SpinCoarseMid.setProperty("value", 93)
        self.SpinCoarseMid.setObjectName("SpinCoarseMid")
        self.gridLayout_14.addWidget(self.SpinCoarseMid, 2, 1, 1, 1)
        self.LblCoarceLow = QtWidgets.QLabel(self.GBCommonVolume)
        self.LblCoarceLow.setObjectName("LblCoarceLow")
        self.gridLayout_14.addWidget(self.LblCoarceLow, 1, 0, 1, 1)
        self.LblCommon = QtWidgets.QLabel(self.GBCommonVolume)
        self.LblCommon.setObjectName("LblCommon")
        self.gridLayout_14.addWidget(self.LblCommon, 0, 0, 1, 1)
        self.LblCOarseMid = QtWidgets.QLabel(self.GBCommonVolume)
        self.LblCOarseMid.setObjectName("LblCOarseMid")
        self.gridLayout_14.addWidget(self.LblCOarseMid, 2, 0, 1, 1)
        self.LblCoarseHigh = QtWidgets.QLabel(self.GBCommonVolume)
        self.LblCoarseHigh.setObjectName("LblCoarseHigh")
        self.gridLayout_14.addWidget(self.LblCoarseHigh, 3, 0, 1, 1)
        self.SpinCoarseHigh = QtWidgets.QSpinBox(self.GBCommonVolume)
        self.SpinCoarseHigh.setMaximum(100)
        self.SpinCoarseHigh.setProperty("value", 100)
        self.SpinCoarseHigh.setObjectName("SpinCoarseHigh")
        self.gridLayout_14.addWidget(self.SpinCoarseHigh, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.GBCommonVolume, 11, 6, 4, 3)
        self.GBCommonSettings = QtWidgets.QGroupBox(self.TabCommon)
        self.GBCommonSettings.setObjectName("GBCommonSettings")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.GBCommonSettings)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.LblPowerOffTimeout = QtWidgets.QLabel(self.GBCommonSettings)
        self.LblPowerOffTimeout.setObjectName("LblPowerOffTimeout")
        self.gridLayout_16.addWidget(self.LblPowerOffTimeout, 0, 0, 1, 1)
        self.SpinPowerOffTimeout = QtWidgets.QSpinBox(self.GBCommonSettings)
        self.SpinPowerOffTimeout.setMaximum(99999)
        self.SpinPowerOffTimeout.setSingleStep(10)
        self.SpinPowerOffTimeout.setProperty("value", 300)
        self.SpinPowerOffTimeout.setObjectName("SpinPowerOffTimeout")
        self.gridLayout_16.addWidget(self.SpinPowerOffTimeout, 0, 1, 1, 1)
        self.LblClashFlashDuration = QtWidgets.QLabel(self.GBCommonSettings)
        self.LblClashFlashDuration.setObjectName("LblClashFlashDuration")
        self.gridLayout_16.addWidget(self.LblClashFlashDuration, 1, 0, 1, 1)
        self.SpinClashFlashDuration = QtWidgets.QSpinBox(self.GBCommonSettings)
        self.SpinClashFlashDuration.setMaximum(99999)
        self.SpinClashFlashDuration.setSingleStep(5)
        self.SpinClashFlashDuration.setProperty("value", 72)
        self.SpinClashFlashDuration.setObjectName("SpinClashFlashDuration")
        self.gridLayout_16.addWidget(self.SpinClashFlashDuration, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.GBCommonSettings, 11, 11, 4, 3)
        self.BtnSave = QtWidgets.QPushButton(self.TabCommon)
        self.BtnSave.setEnabled(False)
        self.BtnSave.setObjectName("BtnSave")
        self.gridLayout_2.addWidget(self.BtnSave, 33, 13, 1, 1, QtCore.Qt.AlignBottom)
        self.GBClash = QtWidgets.QGroupBox(self.TabCommon)
        self.GBClash.setObjectName("GBClash")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.GBClash)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.LblClashHitLevel = QtWidgets.QLabel(self.GBClash)
        self.LblClashHitLevel.setObjectName("LblClashHitLevel")
        self.gridLayout_19.addWidget(self.LblClashHitLevel, 2, 0, 1, 1)
        self.LblClashLength = QtWidgets.QLabel(self.GBClash)
        self.LblClashLength.setObjectName("LblClashLength")
        self.gridLayout_19.addWidget(self.LblClashLength, 1, 0, 1, 1)
        self.SpinClashHitLevel = QtWidgets.QSpinBox(self.GBClash)
        self.SpinClashHitLevel.setMinimum(-1000)
        self.SpinClashHitLevel.setMaximum(1000)
        self.SpinClashHitLevel.setSingleStep(50)
        self.SpinClashHitLevel.setProperty("value", -200)
        self.SpinClashHitLevel.setObjectName("SpinClashHitLevel")
        self.gridLayout_19.addWidget(self.SpinClashHitLevel, 2, 1, 1, 1)
        self.SpinClashHighA = QtWidgets.QSpinBox(self.GBClash)
        self.SpinClashHighA.setMinimum(1000)
        self.SpinClashHighA.setMaximum(9999)
        self.SpinClashHighA.setSingleStep(100)
        self.SpinClashHighA.setProperty("value", 3600)
        self.SpinClashHighA.setObjectName("SpinClashHighA")
        self.gridLayout_19.addWidget(self.SpinClashHighA, 0, 1, 1, 1)
        self.SpinClashLength = QtWidgets.QSpinBox(self.GBClash)
        self.SpinClashLength.setMaximum(9999)
        self.SpinClashLength.setProperty("value", 15)
        self.SpinClashLength.setObjectName("SpinClashLength")
        self.gridLayout_19.addWidget(self.SpinClashLength, 1, 1, 1, 1)
        self.LblClashHighA = QtWidgets.QLabel(self.GBClash)
        self.LblClashHighA.setObjectName("LblClashHighA")
        self.gridLayout_19.addWidget(self.LblClashHighA, 0, 0, 1, 1)
        self.LblClashLowW = QtWidgets.QLabel(self.GBClash)
        self.LblClashLowW.setObjectName("LblClashLowW")
        self.gridLayout_19.addWidget(self.LblClashLowW, 3, 0, 1, 1)
        self.SpinClashLowW = QtWidgets.QSpinBox(self.GBClash)
        self.SpinClashLowW.setProperty("value", 7)
        self.SpinClashLowW.setObjectName("SpinClashLowW")
        self.gridLayout_19.addWidget(self.SpinClashLowW, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.GBClash, 27, 7, 1, 3)
        self.BtnDefault = QtWidgets.QPushButton(self.TabCommon)
        self.BtnDefault.setEnabled(False)
        self.BtnDefault.setObjectName("BtnDefault")
        self.gridLayout_2.addWidget(self.BtnDefault, 33, 12, 1, 1, QtCore.Qt.AlignBottom)
        self.LblCommonStatus = QtWidgets.QLabel(self.TabCommon)
        self.LblCommonStatus.setObjectName("LblCommonStatus")
        self.gridLayout_2.addWidget(self.LblCommonStatus, 33, 2, 1, 1, QtCore.Qt.AlignRight)
        self.tabWidget.addTab(self.TabCommon, "")
        self.TabProfile = QtWidgets.QWidget()
        self.TabProfile.setObjectName("TabProfile")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.TabProfile)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.LblProfile = QtWidgets.QLabel(self.TabProfile)
        self.LblProfile.setObjectName("LblProfile")
        self.gridLayout_3.addWidget(self.LblProfile, 0, 1, 1, 1)
        self.LstProfile = QtWidgets.QListWidget(self.TabProfile)
        self.LstProfile.setObjectName("LstProfile")
        self.gridLayout_3.addWidget(self.LstProfile, 1, 1, 5, 3)
        self.TxtAddProfile = QtWidgets.QLineEdit(self.TabProfile)
        self.TxtAddProfile.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.TxtAddProfile.setObjectName("TxtAddProfile")
        self.gridLayout_3.addWidget(self.TxtAddProfile, 3, 4, 1, 1)
        self.TxtProfileStatus = QtWidgets.QTextBrowser(self.TabProfile)
        self.TxtProfileStatus.setObjectName("TxtProfileStatus")
        self.gridLayout_3.addWidget(self.TxtProfileStatus, 12, 1, 1, 4)
        self.LblProfileStatus = QtWidgets.QLabel(self.TabProfile)
        self.LblProfileStatus.setObjectName("LblProfileStatus")
        self.gridLayout_3.addWidget(self.LblProfileStatus, 11, 1, 1, 1)
        self.BtnProfile = QtWidgets.QPushButton(self.TabProfile)
        self.BtnProfile.setEnabled(False)
        self.BtnProfile.setObjectName("BtnProfile")
        self.gridLayout_3.addWidget(self.BtnProfile, 4, 4, 1, 1)
        self.GBAuxLeds = QtWidgets.QGroupBox(self.TabProfile)
        self.GBAuxLeds.setObjectName("GBAuxLeds")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.GBAuxLeds)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label = QtWidgets.QLabel(self.GBAuxLeds)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 5, 2, 1, 1)
        self.BtnAuxDelete = QtWidgets.QPushButton(self.GBAuxLeds)
        self.BtnAuxDelete.setEnabled(False)
        self.BtnAuxDelete.setObjectName("BtnAuxDelete")
        self.gridLayout_5.addWidget(self.BtnAuxDelete, 10, 2, 1, 1)
        self.ListAuxLeds = QtWidgets.QListView(self.GBAuxLeds)
        self.ListAuxLeds.setObjectName("ListAuxLeds")
        self.gridLayout_5.addWidget(self.ListAuxLeds, 6, 2, 4, 1)
        self.BtnCReateAux = QtWidgets.QPushButton(self.GBAuxLeds)
        self.BtnCReateAux.setObjectName("BtnCReateAux")
        self.gridLayout_5.addWidget(self.BtnCReateAux, 10, 1, 1, 1)
        self.TxtCreateAux = QtWidgets.QLineEdit(self.GBAuxLeds)
        self.TxtCreateAux.setObjectName("TxtCreateAux")
        self.gridLayout_5.addWidget(self.TxtCreateAux, 9, 1, 1, 1)
        self.LblCreateAux = QtWidgets.QLabel(self.GBAuxLeds)
        self.LblCreateAux.setObjectName("LblCreateAux")
        self.gridLayout_5.addWidget(self.LblCreateAux, 8, 1, 1, 1)
        self.CBAuxList = QtWidgets.QComboBox(self.GBAuxLeds)
        self.CBAuxList.setObjectName("CBAuxList")
        self.gridLayout_5.addWidget(self.CBAuxList, 7, 1, 1, 1)
        self.LblAddAux = QtWidgets.QLabel(self.GBAuxLeds)
        self.LblAddAux.setObjectName("LblAddAux")
        self.gridLayout_5.addWidget(self.LblAddAux, 6, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(1, 15)
        self.gridLayout_5.setColumnStretch(2, 10)
        self.gridLayout_3.addWidget(self.GBAuxLeds, 10, 4, 1, 1)
        self.LblProfile_2 = QtWidgets.QLabel(self.TabProfile)
        self.LblProfile_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.LblProfile_2.setObjectName("LblProfile_2")
        self.gridLayout_3.addWidget(self.LblProfile_2, 2, 4, 1, 1)
        self.BtnDeleteProfile = QtWidgets.QPushButton(self.TabProfile)
        self.BtnDeleteProfile.setEnabled(False)
        self.BtnDeleteProfile.setObjectName("BtnDeleteProfile")
        self.gridLayout_3.addWidget(self.BtnDeleteProfile, 5, 4, 1, 1)
        self.CBIndicate = QtWidgets.QCheckBox(self.TabProfile)
        self.CBIndicate.setEnabled(False)
        self.CBIndicate.setChecked(True)
        self.CBIndicate.setObjectName("CBIndicate")
        self.gridLayout_3.addWidget(self.CBIndicate, 7, 1, 1, 1)
        self.CBBlade = QtWidgets.QComboBox(self.TabProfile)
        self.CBBlade.setEnabled(False)
        self.CBBlade.setObjectName("CBBlade")
        self.CBBlade.addItem("")
        self.CBBlade.addItem("")
        self.gridLayout_3.addWidget(self.CBBlade, 6, 1, 1, 3)
        self.LblDelayBeforeOn = QtWidgets.QLabel(self.TabProfile)
        self.LblDelayBeforeOn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LblDelayBeforeOn.setObjectName("LblDelayBeforeOn")
        self.gridLayout_3.addWidget(self.LblDelayBeforeOn, 7, 2, 1, 1)
        self.SpinDelayBeforeOn = QtWidgets.QSpinBox(self.TabProfile)
        self.SpinDelayBeforeOn.setEnabled(False)
        self.SpinDelayBeforeOn.setMaximum(9999)
        self.SpinDelayBeforeOn.setSingleStep(100)
        self.SpinDelayBeforeOn.setProperty("value", 200)
        self.SpinDelayBeforeOn.setObjectName("SpinDelayBeforeOn")
        self.gridLayout_3.addWidget(self.SpinDelayBeforeOn, 7, 3, 1, 1)
        self.TabEffects = QtWidgets.QTabWidget(self.TabProfile)
        self.TabEffects.setEnabled(True)
        self.TabEffects.setObjectName("TabEffects")
        self.TabAfterWake = QtWidgets.QWidget()
        self.TabAfterWake.setObjectName("TabAfterWake")
        self.TabEffects.addTab(self.TabAfterWake, "")
        self.TabPowerOn = QtWidgets.QWidget()
        self.TabPowerOn.setObjectName("TabPowerOn")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.TabPowerOn)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.LBLBladeSpeed = QtWidgets.QLabel(self.TabPowerOn)
        self.LBLBladeSpeed.setObjectName("LBLBladeSpeed")
        self.gridLayout_6.addWidget(self.LBLBladeSpeed, 0, 0, 1, 1)
        self.SpinBladeSpeedOn = QtWidgets.QSpinBox(self.TabPowerOn)
        self.SpinBladeSpeedOn.setEnabled(False)
        self.SpinBladeSpeedOn.setMinimum(1)
        self.SpinBladeSpeedOn.setMaximum(144)
        self.SpinBladeSpeedOn.setProperty("value", 144)
        self.SpinBladeSpeedOn.setObjectName("SpinBladeSpeedOn")
        self.gridLayout_6.addWidget(self.SpinBladeSpeedOn, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem2, 1, 0, 1, 1)
        self.TabEffects.addTab(self.TabPowerOn, "")
        self.TabWorkingMode = QtWidgets.QWidget()
        self.TabWorkingMode.setObjectName("TabWorkingMode")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.TabWorkingMode)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.LblWorkingColor = QtWidgets.QLabel(self.TabWorkingMode)
        self.LblWorkingColor.setObjectName("LblWorkingColor")
        self.gridLayout_4.addWidget(self.LblWorkingColor, 0, 0, 1, 1, QtCore.Qt.AlignBottom)
        self.TxtWorkingColor = QtWidgets.QLineEdit(self.TabWorkingMode)
        self.TxtWorkingColor.setEnabled(False)
        self.TxtWorkingColor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TxtWorkingColor.setObjectName("TxtWorkingColor")
        self.gridLayout_4.addWidget(self.TxtWorkingColor, 1, 0, 1, 1)
        self.BtnWorkingColor = QtWidgets.QPushButton(self.TabWorkingMode)
        self.BtnWorkingColor.setEnabled(False)
        self.BtnWorkingColor.setObjectName("BtnWorkingColor")
        self.gridLayout_4.addWidget(self.BtnWorkingColor, 2, 0, 1, 1)
        self.CBFlickering = QtWidgets.QCheckBox(self.TabWorkingMode)
        self.CBFlickering.setEnabled(False)
        self.CBFlickering.setChecked(True)
        self.CBFlickering.setObjectName("CBFlickering")
        self.gridLayout_4.addWidget(self.CBFlickering, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 1, 1, 1, 1)
        self.CBFlaming = QtWidgets.QCheckBox(self.TabWorkingMode)
        self.CBFlaming.setEnabled(False)
        self.CBFlaming.setObjectName("CBFlaming")
        self.gridLayout_4.addWidget(self.CBFlaming, 3, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_4.addLayout(self.verticalLayout, 6, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 5, 0, 1, 1)
        self.TabEffects.addTab(self.TabWorkingMode, "")
        self.TabPowerOff = QtWidgets.QWidget()
        self.TabPowerOff.setObjectName("TabPowerOff")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.TabPowerOff)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.SpinPowerOffSpeed = QtWidgets.QSpinBox(self.TabPowerOff)
        self.SpinPowerOffSpeed.setEnabled(False)
        self.SpinPowerOffSpeed.setMinimum(1)
        self.SpinPowerOffSpeed.setMaximum(144)
        self.SpinPowerOffSpeed.setProperty("value", 144)
        self.SpinPowerOffSpeed.setObjectName("SpinPowerOffSpeed")
        self.gridLayout_9.addWidget(self.SpinPowerOffSpeed, 1, 1, 1, 1)
        self.LblPowerOnSpeed = QtWidgets.QLabel(self.TabPowerOff)
        self.LblPowerOnSpeed.setObjectName("LblPowerOnSpeed")
        self.gridLayout_9.addWidget(self.LblPowerOnSpeed, 1, 0, 1, 1)
        self.CBMoveForward = QtWidgets.QCheckBox(self.TabPowerOff)
        self.CBMoveForward.setObjectName("CBMoveForward")
        self.gridLayout_9.addWidget(self.CBMoveForward, 2, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem6, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem7, 3, 0, 1, 1)
        self.TabEffects.addTab(self.TabPowerOff, "")
        self.TabFlaming = QtWidgets.QWidget()
        self.TabFlaming.setObjectName("TabFlaming")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.TabFlaming)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem8, 2, 9, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem9, 2, 3, 1, 1)
        self.LblFlamingDelayMin = QtWidgets.QLabel(self.TabFlaming)
        self.LblFlamingDelayMin.setObjectName("LblFlamingDelayMin")
        self.gridLayout_10.addWidget(self.LblFlamingDelayMin, 2, 7, 1, 1)
        self.SpinFlamingSpeedMax = QtWidgets.QSpinBox(self.TabFlaming)
        self.SpinFlamingSpeedMax.setEnabled(False)
        self.SpinFlamingSpeedMax.setMinimum(12)
        self.SpinFlamingSpeedMax.setMaximum(144)
        self.SpinFlamingSpeedMax.setProperty("value", 27)
        self.SpinFlamingSpeedMax.setObjectName("SpinFlamingSpeedMax")
        self.gridLayout_10.addWidget(self.SpinFlamingSpeedMax, 3, 5, 1, 1)
        self.LblFlamingDelayMax = QtWidgets.QLabel(self.TabFlaming)
        self.LblFlamingDelayMax.setObjectName("LblFlamingDelayMax")
        self.gridLayout_10.addWidget(self.LblFlamingDelayMax, 3, 7, 1, 1)
        self.LblFlamingDelay = QtWidgets.QLabel(self.TabFlaming)
        self.LblFlamingDelay.setObjectName("LblFlamingDelay")
        self.gridLayout_10.addWidget(self.LblFlamingDelay, 1, 7, 1, 1)
        self.BtnAddColor = QtWidgets.QPushButton(self.TabFlaming)
        self.BtnAddColor.setEnabled(False)
        self.BtnAddColor.setObjectName("BtnAddColor")
        self.gridLayout_10.addWidget(self.BtnAddColor, 5, 11, 1, 1)
        self.BtnDeleteColor = QtWidgets.QPushButton(self.TabFlaming)
        self.BtnDeleteColor.setEnabled(False)
        self.BtnDeleteColor.setObjectName("BtnDeleteColor")
        self.gridLayout_10.addWidget(self.BtnDeleteColor, 5, 10, 1, 1)
        self.LblFlamingColors = QtWidgets.QLabel(self.TabFlaming)
        self.LblFlamingColors.setObjectName("LblFlamingColors")
        self.gridLayout_10.addWidget(self.LblFlamingColors, 1, 10, 1, 1)
        self.SpinFlamingSizeMin = QtWidgets.QSpinBox(self.TabFlaming)
        self.SpinFlamingSizeMin.setEnabled(False)
        self.SpinFlamingSizeMin.setMinimum(1)
        self.SpinFlamingSizeMin.setMaximum(9)
        self.SpinFlamingSizeMin.setProperty("value", 2)
        self.SpinFlamingSizeMin.setObjectName("SpinFlamingSizeMin")
        self.gridLayout_10.addWidget(self.SpinFlamingSizeMin, 2, 2, 1, 1)
        self.SpinFlamingDelayMin = QtWidgets.QSpinBox(self.TabFlaming)
        self.SpinFlamingDelayMin.setEnabled(False)
        self.SpinFlamingDelayMin.setMinimum(1)
        self.SpinFlamingDelayMin.setMaximum(180)
        self.SpinFlamingDelayMin.setSingleStep(10)
        self.SpinFlamingDelayMin.setProperty("value", 54)
        self.SpinFlamingDelayMin.setObjectName("SpinFlamingDelayMin")
        self.gridLayout_10.addWidget(self.SpinFlamingDelayMin, 2, 8, 1, 1)
        self.SpinFlamingSpeedMin = QtWidgets.QSpinBox(self.TabFlaming)
        self.SpinFlamingSpeedMin.setEnabled(False)
        self.SpinFlamingSpeedMin.setMinimum(1)
        self.SpinFlamingSpeedMin.setMaximum(27)
        self.SpinFlamingSpeedMin.setProperty("value", 12)
        self.SpinFlamingSpeedMin.setObjectName("SpinFlamingSpeedMin")
        self.gridLayout_10.addWidget(self.SpinFlamingSpeedMin, 2, 5, 1, 1)
        self.SpinFlamingDelayMax = QtWidgets.QSpinBox(self.TabFlaming)
        self.SpinFlamingDelayMax.setEnabled(False)
        self.SpinFlamingDelayMax.setMinimum(54)
        self.SpinFlamingDelayMax.setMaximum(9999)
        self.SpinFlamingDelayMax.setSingleStep(10)
        self.SpinFlamingDelayMax.setProperty("value", 180)
        self.SpinFlamingDelayMax.setObjectName("SpinFlamingDelayMax")
        self.gridLayout_10.addWidget(self.SpinFlamingDelayMax, 3, 8, 1, 1)
        self.LblFlamingSpeedMax = QtWidgets.QLabel(self.TabFlaming)
        self.LblFlamingSpeedMax.setObjectName("LblFlamingSpeedMax")
        self.gridLayout_10.addWidget(self.LblFlamingSpeedMax, 3, 4, 1, 1)
        self.LblFlamigSize = QtWidgets.QLabel(self.TabFlaming)
        self.LblFlamigSize.setObjectName("LblFlamigSize")
        self.gridLayout_10.addWidget(self.LblFlamigSize, 1, 1, 1, 1)
        self.SpinFlamingSizeMax = QtWidgets.QSpinBox(self.TabFlaming)
        self.SpinFlamingSizeMax.setEnabled(False)
        self.SpinFlamingSizeMax.setMinimum(2)
        self.SpinFlamingSizeMax.setMaximum(144)
        self.SpinFlamingSizeMax.setProperty("value", 9)
        self.SpinFlamingSizeMax.setObjectName("SpinFlamingSizeMax")
        self.gridLayout_10.addWidget(self.SpinFlamingSizeMax, 3, 2, 1, 1)
        self.LblFlamingSizeMax = QtWidgets.QLabel(self.TabFlaming)
        self.LblFlamingSizeMax.setObjectName("LblFlamingSizeMax")
        self.gridLayout_10.addWidget(self.LblFlamingSizeMax, 3, 1, 1, 1)
        self.LblFlamingSpeed = QtWidgets.QLabel(self.TabFlaming)
        self.LblFlamingSpeed.setObjectName("LblFlamingSpeed")
        self.gridLayout_10.addWidget(self.LblFlamingSpeed, 1, 4, 1, 1)
        self.LblFlamingSizeMin = QtWidgets.QLabel(self.TabFlaming)
        self.LblFlamingSizeMin.setObjectName("LblFlamingSizeMin")
        self.gridLayout_10.addWidget(self.LblFlamingSizeMin, 2, 1, 1, 1)
        self.LblFlamingSpeedMin = QtWidgets.QLabel(self.TabFlaming)
        self.LblFlamingSpeedMin.setObjectName("LblFlamingSpeedMin")
        self.gridLayout_10.addWidget(self.LblFlamingSpeedMin, 2, 4, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem10, 2, 6, 1, 1)
        self.LstFlamingColor = QtWidgets.QListWidget(self.TabFlaming)
        self.LstFlamingColor.setObjectName("LstFlamingColor")
        self.gridLayout_10.addWidget(self.LstFlamingColor, 2, 10, 2, 2)
        self.CBFlamingAlwaysOn = QtWidgets.QCheckBox(self.TabFlaming)
        self.CBFlamingAlwaysOn.setEnabled(False)
        self.CBFlamingAlwaysOn.setObjectName("CBFlamingAlwaysOn")
        self.gridLayout_10.addWidget(self.CBFlamingAlwaysOn, 0, 1, 1, 1)
        self.TabEffects.addTab(self.TabFlaming, "")
        self.TabFlickering = QtWidgets.QWidget()
        self.TabFlickering.setObjectName("TabFlickering")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.TabFlickering)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.SpinFlickeringTimeMax = QtWidgets.QSpinBox(self.TabFlickering)
        self.SpinFlickeringTimeMax.setEnabled(False)
        self.SpinFlickeringTimeMax.setMinimum(90)
        self.SpinFlickeringTimeMax.setMaximum(99999)
        self.SpinFlickeringTimeMax.setSingleStep(10)
        self.SpinFlickeringTimeMax.setProperty("value", 360)
        self.SpinFlickeringTimeMax.setObjectName("SpinFlickeringTimeMax")
        self.gridLayout_11.addWidget(self.SpinFlickeringTimeMax, 3, 1, 1, 1)
        self.SpinFlickeringTimeMin = QtWidgets.QSpinBox(self.TabFlickering)
        self.SpinFlickeringTimeMin.setEnabled(False)
        self.SpinFlickeringTimeMin.setMinimum(1)
        self.SpinFlickeringTimeMin.setMaximum(360)
        self.SpinFlickeringTimeMin.setSingleStep(10)
        self.SpinFlickeringTimeMin.setProperty("value", 90)
        self.SpinFlickeringTimeMin.setObjectName("SpinFlickeringTimeMin")
        self.gridLayout_11.addWidget(self.SpinFlickeringTimeMin, 2, 1, 1, 1)
        self.LblFlickeringBrMin = QtWidgets.QLabel(self.TabFlickering)
        self.LblFlickeringBrMin.setObjectName("LblFlickeringBrMin")
        self.gridLayout_11.addWidget(self.LblFlickeringBrMin, 2, 2, 1, 1)
        self.SpinFlickeringBrMax = QtWidgets.QSpinBox(self.TabFlickering)
        self.SpinFlickeringBrMax.setEnabled(False)
        self.SpinFlickeringBrMax.setMinimum(50)
        self.SpinFlickeringBrMax.setMaximum(100)
        self.SpinFlickeringBrMax.setProperty("value", 100)
        self.SpinFlickeringBrMax.setObjectName("SpinFlickeringBrMax")
        self.gridLayout_11.addWidget(self.SpinFlickeringBrMax, 3, 3, 1, 1)
        self.LblFlickeringBrMax = QtWidgets.QLabel(self.TabFlickering)
        self.LblFlickeringBrMax.setObjectName("LblFlickeringBrMax")
        self.gridLayout_11.addWidget(self.LblFlickeringBrMax, 3, 2, 1, 1)
        self.SpinFlickeringBrMin = QtWidgets.QSpinBox(self.TabFlickering)
        self.SpinFlickeringBrMin.setEnabled(False)
        self.SpinFlickeringBrMin.setMinimum(0)
        self.SpinFlickeringBrMin.setMaximum(100)
        self.SpinFlickeringBrMin.setProperty("value", 50)
        self.SpinFlickeringBrMin.setObjectName("SpinFlickeringBrMin")
        self.gridLayout_11.addWidget(self.SpinFlickeringBrMin, 2, 3, 1, 1)
        self.LblFlickeringSizeMax = QtWidgets.QLabel(self.TabFlickering)
        self.LblFlickeringSizeMax.setObjectName("LblFlickeringSizeMax")
        self.gridLayout_11.addWidget(self.LblFlickeringSizeMax, 3, 0, 1, 1)
        self.LblFlickeringSizeMin = QtWidgets.QLabel(self.TabFlickering)
        self.LblFlickeringSizeMin.setObjectName("LblFlickeringSizeMin")
        self.gridLayout_11.addWidget(self.LblFlickeringSizeMin, 2, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem11, 2, 4, 1, 1)
        self.LblFlickeringBrigtness = QtWidgets.QLabel(self.TabFlickering)
        self.LblFlickeringBrigtness.setObjectName("LblFlickeringBrigtness")
        self.gridLayout_11.addWidget(self.LblFlickeringBrigtness, 1, 2, 1, 1)
        self.LblFlickeringTime = QtWidgets.QLabel(self.TabFlickering)
        self.LblFlickeringTime.setObjectName("LblFlickeringTime")
        self.gridLayout_11.addWidget(self.LblFlickeringTime, 1, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem12, 4, 2, 1, 1)
        self.CBFlickeringAlwaysOn = QtWidgets.QCheckBox(self.TabFlickering)
        self.CBFlickeringAlwaysOn.setEnabled(False)
        self.CBFlickeringAlwaysOn.setObjectName("CBFlickeringAlwaysOn")
        self.gridLayout_11.addWidget(self.CBFlickeringAlwaysOn, 0, 0, 1, 1)
        self.TabEffects.addTab(self.TabFlickering, "")
        self.TabBlaster = QtWidgets.QWidget()
        self.TabBlaster.setObjectName("TabBlaster")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.TabBlaster)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.SpinBlasterDuration = QtWidgets.QSpinBox(self.TabBlaster)
        self.SpinBlasterDuration.setEnabled(False)
        self.SpinBlasterDuration.setMinimum(1)
        self.SpinBlasterDuration.setMaximum(9999)
        self.SpinBlasterDuration.setSingleStep(10)
        self.SpinBlasterDuration.setProperty("value", 720)
        self.SpinBlasterDuration.setObjectName("SpinBlasterDuration")
        self.gridLayout_12.addWidget(self.SpinBlasterDuration, 1, 2, 1, 1)
        self.LBBlasterColor = QtWidgets.QLabel(self.TabBlaster)
        self.LBBlasterColor.setObjectName("LBBlasterColor")
        self.gridLayout_12.addWidget(self.LBBlasterColor, 0, 0, 1, 1)
        self.BtnBlasterColor = QtWidgets.QPushButton(self.TabBlaster)
        self.BtnBlasterColor.setEnabled(False)
        self.BtnBlasterColor.setObjectName("BtnBlasterColor")
        self.gridLayout_12.addWidget(self.BtnBlasterColor, 2, 0, 1, 1)
        self.TxtBlasterColor = QtWidgets.QLineEdit(self.TabBlaster)
        self.TxtBlasterColor.setEnabled(False)
        self.TxtBlasterColor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TxtBlasterColor.setObjectName("TxtBlasterColor")
        self.gridLayout_12.addWidget(self.TxtBlasterColor, 1, 0, 1, 1)
        self.LblBlasterDuration = QtWidgets.QLabel(self.TabBlaster)
        self.LblBlasterDuration.setObjectName("LblBlasterDuration")
        self.gridLayout_12.addWidget(self.LblBlasterDuration, 1, 1, 1, 1)
        self.SpinBlasterSizePix = QtWidgets.QSpinBox(self.TabBlaster)
        self.SpinBlasterSizePix.setEnabled(False)
        self.SpinBlasterSizePix.setMinimum(1)
        self.SpinBlasterSizePix.setMaximum(144)
        self.SpinBlasterSizePix.setProperty("value", 7)
        self.SpinBlasterSizePix.setObjectName("SpinBlasterSizePix")
        self.gridLayout_12.addWidget(self.SpinBlasterSizePix, 2, 2, 1, 1)
        self.LblSizePixDuration = QtWidgets.QLabel(self.TabBlaster)
        self.LblSizePixDuration.setObjectName("LblSizePixDuration")
        self.gridLayout_12.addWidget(self.LblSizePixDuration, 2, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem13, 1, 4, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem14, 3, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem15, 1, 3, 1, 1)
        self.TabEffects.addTab(self.TabBlaster, "")
        self.TabClash = QtWidgets.QWidget()
        self.TabClash.setObjectName("TabClash")
        self.layoutWidget = QtWidgets.QWidget(self.TabClash)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_21.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem16, 1, 4, 1, 1)
        self.LblClashSizePix = QtWidgets.QLabel(self.layoutWidget)
        self.LblClashSizePix.setObjectName("LblClashSizePix")
        self.gridLayout_21.addWidget(self.LblClashSizePix, 2, 1, 1, 1)
        self.BtnClashColor = QtWidgets.QPushButton(self.layoutWidget)
        self.BtnClashColor.setEnabled(False)
        self.BtnClashColor.setObjectName("BtnClashColor")
        self.gridLayout_21.addWidget(self.BtnClashColor, 2, 0, 1, 1)
        self.LblClashDuration = QtWidgets.QLabel(self.layoutWidget)
        self.LblClashDuration.setObjectName("LblClashDuration")
        self.gridLayout_21.addWidget(self.LblClashDuration, 1, 1, 1, 1)
        self.TxtClashColor = QtWidgets.QLineEdit(self.layoutWidget)
        self.TxtClashColor.setEnabled(False)
        self.TxtClashColor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TxtClashColor.setObjectName("TxtClashColor")
        self.gridLayout_21.addWidget(self.TxtClashColor, 1, 0, 1, 1)
        self.SpinClashDuration = QtWidgets.QSpinBox(self.layoutWidget)
        self.SpinClashDuration.setEnabled(False)
        self.SpinClashDuration.setMinimum(1)
        self.SpinClashDuration.setMaximum(9999)
        self.SpinClashDuration.setSingleStep(10)
        self.SpinClashDuration.setProperty("value", 720)
        self.SpinClashDuration.setObjectName("SpinClashDuration")
        self.gridLayout_21.addWidget(self.SpinClashDuration, 1, 2, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem17, 3, 0, 1, 1)
        self.SpinClashSizePix = QtWidgets.QSpinBox(self.layoutWidget)
        self.SpinClashSizePix.setEnabled(False)
        self.SpinClashSizePix.setMinimum(1)
        self.SpinClashSizePix.setMaximum(144)
        self.SpinClashSizePix.setProperty("value", 7)
        self.SpinClashSizePix.setObjectName("SpinClashSizePix")
        self.gridLayout_21.addWidget(self.SpinClashSizePix, 2, 2, 1, 1)
        self.LblClashCOlor = QtWidgets.QLabel(self.layoutWidget)
        self.LblClashCOlor.setObjectName("LblClashCOlor")
        self.gridLayout_21.addWidget(self.LblClashCOlor, 0, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem18, 1, 3, 1, 1)
        self.TabEffects.addTab(self.TabClash, "")
        self.TabStab = QtWidgets.QWidget()
        self.TabStab.setObjectName("TabStab")
        self.layoutWidget1 = QtWidgets.QWidget(self.TabStab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 781, 151))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_22.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.LblStabColor = QtWidgets.QLabel(self.layoutWidget1)
        self.LblStabColor.setObjectName("LblStabColor")
        self.gridLayout_22.addWidget(self.LblStabColor, 0, 0, 1, 1)
        self.TxtStabColor = QtWidgets.QLineEdit(self.layoutWidget1)
        self.TxtStabColor.setEnabled(False)
        self.TxtStabColor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TxtStabColor.setObjectName("TxtStabColor")
        self.gridLayout_22.addWidget(self.TxtStabColor, 1, 0, 1, 1)
        self.LblStabDuration = QtWidgets.QLabel(self.layoutWidget1)
        self.LblStabDuration.setObjectName("LblStabDuration")
        self.gridLayout_22.addWidget(self.LblStabDuration, 1, 1, 1, 1)
        self.SpinStabDuration = QtWidgets.QSpinBox(self.layoutWidget1)
        self.SpinStabDuration.setEnabled(False)
        self.SpinStabDuration.setMinimum(1)
        self.SpinStabDuration.setMaximum(999)
        self.SpinStabDuration.setSingleStep(10)
        self.SpinStabDuration.setProperty("value", 720)
        self.SpinStabDuration.setObjectName("SpinStabDuration")
        self.gridLayout_22.addWidget(self.SpinStabDuration, 1, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem19, 1, 4, 1, 1)
        self.BtnStabColor = QtWidgets.QPushButton(self.layoutWidget1)
        self.BtnStabColor.setEnabled(False)
        self.BtnStabColor.setObjectName("BtnStabColor")
        self.gridLayout_22.addWidget(self.BtnStabColor, 2, 0, 1, 1)
        self.LblStabSizePix = QtWidgets.QLabel(self.layoutWidget1)
        self.LblStabSizePix.setObjectName("LblStabSizePix")
        self.gridLayout_22.addWidget(self.LblStabSizePix, 2, 1, 1, 1)
        self.SpinStabSizePix = QtWidgets.QSpinBox(self.layoutWidget1)
        self.SpinStabSizePix.setEnabled(False)
        self.SpinStabSizePix.setMinimum(1)
        self.SpinStabSizePix.setMaximum(144)
        self.SpinStabSizePix.setSingleStep(1)
        self.SpinStabSizePix.setProperty("value", 11)
        self.SpinStabSizePix.setObjectName("SpinStabSizePix")
        self.gridLayout_22.addWidget(self.SpinStabSizePix, 2, 2, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_22.addItem(spacerItem20, 3, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem21, 1, 3, 1, 1)
        self.TabEffects.addTab(self.TabStab, "")
        self.TabLockup = QtWidgets.QWidget()
        self.TabLockup.setObjectName("TabLockup")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.TabLockup)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.SpinLockupPeriodMax = QtWidgets.QSpinBox(self.TabLockup)
        self.SpinLockupPeriodMax.setEnabled(False)
        self.SpinLockupPeriodMax.setMinimum(15)
        self.SpinLockupPeriodMax.setMaximum(9999)
        self.SpinLockupPeriodMax.setSingleStep(5)
        self.SpinLockupPeriodMax.setProperty("value", 25)
        self.SpinLockupPeriodMax.setObjectName("SpinLockupPeriodMax")
        self.gridLayout_23.addWidget(self.SpinLockupPeriodMax, 4, 8, 1, 1)
        self.TxtLockupFlashesColor = QtWidgets.QLineEdit(self.TabLockup)
        self.TxtLockupFlashesColor.setEnabled(False)
        self.TxtLockupFlashesColor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TxtLockupFlashesColor.setObjectName("TxtLockupFlashesColor")
        self.gridLayout_23.addWidget(self.TxtLockupFlashesColor, 3, 6, 1, 1)
        self.BtnLockupFlickerColor = QtWidgets.QPushButton(self.TabLockup)
        self.BtnLockupFlickerColor.setEnabled(False)
        self.BtnLockupFlickerColor.setObjectName("BtnLockupFlickerColor")
        self.gridLayout_23.addWidget(self.BtnLockupFlickerColor, 4, 0, 1, 1)
        self.LblLockupTimeMin = QtWidgets.QLabel(self.TabLockup)
        self.LblLockupTimeMin.setObjectName("LblLockupTimeMin")
        self.gridLayout_23.addWidget(self.LblLockupTimeMin, 3, 1, 1, 1)
        self.LblLockupTime = QtWidgets.QLabel(self.TabLockup)
        self.LblLockupTime.setObjectName("LblLockupTime")
        self.gridLayout_23.addWidget(self.LblLockupTime, 1, 1, 1, 1)
        self.SpinLockupTimeMin = QtWidgets.QSpinBox(self.TabLockup)
        self.SpinLockupTimeMin.setEnabled(False)
        self.SpinLockupTimeMin.setMinimum(1)
        self.SpinLockupTimeMin.setMaximum(80)
        self.SpinLockupTimeMin.setProperty("value", 45)
        self.SpinLockupTimeMin.setObjectName("SpinLockupTimeMin")
        self.gridLayout_23.addWidget(self.SpinLockupTimeMin, 3, 2, 1, 1)
        self.LblLockupFlickerColor = QtWidgets.QLabel(self.TabLockup)
        self.LblLockupFlickerColor.setObjectName("LblLockupFlickerColor")
        self.gridLayout_23.addWidget(self.LblLockupFlickerColor, 1, 0, 1, 1)
        self.LblLockupTimeMax = QtWidgets.QLabel(self.TabLockup)
        self.LblLockupTimeMax.setObjectName("LblLockupTimeMax")
        self.gridLayout_23.addWidget(self.LblLockupTimeMax, 4, 1, 1, 1)
        self.SpinLockupSizepix = QtWidgets.QSpinBox(self.TabLockup)
        self.SpinLockupSizepix.setEnabled(False)
        self.SpinLockupSizepix.setMinimum(1)
        self.SpinLockupSizepix.setMaximum(144)
        self.SpinLockupSizepix.setSingleStep(1)
        self.SpinLockupSizepix.setProperty("value", 7)
        self.SpinLockupSizepix.setObjectName("SpinLockupSizepix")
        self.gridLayout_23.addWidget(self.SpinLockupSizepix, 4, 10, 1, 1)
        self.LblLockupPeriod = QtWidgets.QLabel(self.TabLockup)
        self.LblLockupPeriod.setObjectName("LblLockupPeriod")
        self.gridLayout_23.addWidget(self.LblLockupPeriod, 1, 7, 1, 1)
        self.TxtLockupFlickerColor = QtWidgets.QLineEdit(self.TabLockup)
        self.TxtLockupFlickerColor.setEnabled(False)
        self.TxtLockupFlickerColor.setInputMask("")
        self.TxtLockupFlickerColor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.TxtLockupFlickerColor.setObjectName("TxtLockupFlickerColor")
        self.gridLayout_23.addWidget(self.TxtLockupFlickerColor, 3, 0, 1, 1)
        self.BtnLockupFlashesColor = QtWidgets.QPushButton(self.TabLockup)
        self.BtnLockupFlashesColor.setEnabled(False)
        self.BtnLockupFlashesColor.setObjectName("BtnLockupFlashesColor")
        self.gridLayout_23.addWidget(self.BtnLockupFlashesColor, 4, 6, 1, 1)
        self.LblLockupDuration = QtWidgets.QLabel(self.TabLockup)
        self.LblLockupDuration.setObjectName("LblLockupDuration")
        self.gridLayout_23.addWidget(self.LblLockupDuration, 3, 9, 1, 1)
        self.SpinLockupPeriodMin = QtWidgets.QSpinBox(self.TabLockup)
        self.SpinLockupPeriodMin.setEnabled(False)
        self.SpinLockupPeriodMin.setMinimum(1)
        self.SpinLockupPeriodMin.setMaximum(15)
        self.SpinLockupPeriodMin.setSingleStep(1)
        self.SpinLockupPeriodMin.setProperty("value", 15)
        self.SpinLockupPeriodMin.setObjectName("SpinLockupPeriodMin")
        self.gridLayout_23.addWidget(self.SpinLockupPeriodMin, 3, 8, 1, 1)
        self.SpinLockupDuration = QtWidgets.QSpinBox(self.TabLockup)
        self.SpinLockupDuration.setEnabled(False)
        self.SpinLockupDuration.setMinimum(1)
        self.SpinLockupDuration.setMaximum(9999)
        self.SpinLockupDuration.setSingleStep(10)
        self.SpinLockupDuration.setProperty("value", 50)
        self.SpinLockupDuration.setObjectName("SpinLockupDuration")
        self.gridLayout_23.addWidget(self.SpinLockupDuration, 3, 10, 1, 1)
        self.LblLockupSizepix = QtWidgets.QLabel(self.TabLockup)
        self.LblLockupSizepix.setObjectName("LblLockupSizepix")
        self.gridLayout_23.addWidget(self.LblLockupSizepix, 4, 9, 1, 1)
        self.LblLockupPeriodMin = QtWidgets.QLabel(self.TabLockup)
        self.LblLockupPeriodMin.setObjectName("LblLockupPeriodMin")
        self.gridLayout_23.addWidget(self.LblLockupPeriodMin, 3, 7, 1, 1)
        self.SpinLockupBrightnessMax = QtWidgets.QSpinBox(self.TabLockup)
        self.SpinLockupBrightnessMax.setEnabled(False)
        self.SpinLockupBrightnessMax.setMinimum(50)
        self.SpinLockupBrightnessMax.setMaximum(100)
        self.SpinLockupBrightnessMax.setProperty("value", 100)
        self.SpinLockupBrightnessMax.setObjectName("SpinLockupBrightnessMax")
        self.gridLayout_23.addWidget(self.SpinLockupBrightnessMax, 4, 4, 1, 1)
        self.LblLockcupBrightnessMax = QtWidgets.QLabel(self.TabLockup)
        self.LblLockcupBrightnessMax.setObjectName("LblLockcupBrightnessMax")
        self.gridLayout_23.addWidget(self.LblLockcupBrightnessMax, 4, 3, 1, 1)
        self.LblLockupFlicker = QtWidgets.QLabel(self.TabLockup)
        self.LblLockupFlicker.setObjectName("LblLockupFlicker")
        self.gridLayout_23.addWidget(self.LblLockupFlicker, 0, 0, 1, 1)
        self.LblLockupFlashes = QtWidgets.QLabel(self.TabLockup)
        self.LblLockupFlashes.setObjectName("LblLockupFlashes")
        self.gridLayout_23.addWidget(self.LblLockupFlashes, 0, 6, 1, 1)
        self.LblLockupBrightness = QtWidgets.QLabel(self.TabLockup)
        self.LblLockupBrightness.setObjectName("LblLockupBrightness")
        self.gridLayout_23.addWidget(self.LblLockupBrightness, 1, 3, 1, 1)
        self.LblLockupFlashesColor = QtWidgets.QLabel(self.TabLockup)
        self.LblLockupFlashesColor.setObjectName("LblLockupFlashesColor")
        self.gridLayout_23.addWidget(self.LblLockupFlashesColor, 1, 6, 1, 1)
        self.SpinLockupTimeMax = QtWidgets.QSpinBox(self.TabLockup)
        self.SpinLockupTimeMax.setEnabled(False)
        self.SpinLockupTimeMax.setMinimum(45)
        self.SpinLockupTimeMax.setMaximum(9999)
        self.SpinLockupTimeMax.setProperty("value", 80)
        self.SpinLockupTimeMax.setObjectName("SpinLockupTimeMax")
        self.gridLayout_23.addWidget(self.SpinLockupTimeMax, 4, 2, 1, 1)
        self.SpinLockupBrightnessMin = QtWidgets.QSpinBox(self.TabLockup)
        self.SpinLockupBrightnessMin.setEnabled(False)
        self.SpinLockupBrightnessMin.setMaximum(100)
        self.SpinLockupBrightnessMin.setProperty("value", 50)
        self.SpinLockupBrightnessMin.setObjectName("SpinLockupBrightnessMin")
        self.gridLayout_23.addWidget(self.SpinLockupBrightnessMin, 3, 4, 1, 1)
        self.LblLockupBrightnessMin = QtWidgets.QLabel(self.TabLockup)
        self.LblLockupBrightnessMin.setObjectName("LblLockupBrightnessMin")
        self.gridLayout_23.addWidget(self.LblLockupBrightnessMin, 3, 3, 1, 1)
        self.LblLockupPeriodMax = QtWidgets.QLabel(self.TabLockup)
        self.LblLockupPeriodMax.setObjectName("LblLockupPeriodMax")
        self.gridLayout_23.addWidget(self.LblLockupPeriodMax, 4, 7, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem22, 4, 5, 1, 1)
        self.TabEffects.addTab(self.TabLockup, "")
        self.gridLayout_3.addWidget(self.TabEffects, 9, 1, 2, 3)
        self.tabWidget.addTab(self.TabProfile, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAuxLeds_Editor_Help = QtWidgets.QAction(MainWindow)
        self.actionAuxLeds_Editor_Help.setObjectName("actionAuxLeds_Editor_Help")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAuxLeds_Editor_Help)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.TabEffects.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SettingsEditor"))
        self.BtnEdit.setText(_translate("MainWindow", "Edit"))
        self.BtnCreate.setText(_translate("MainWindow", "Create Effect"))
        self.LBLLed2_2.setText(_translate("MainWindow", "LED2:"))
        self.LBLLed7_2.setText(_translate("MainWindow", "LED7:"))
        self.BtnRepeat.setText(_translate("MainWindow", "AddRepeat"))
        self.LBLLed6_2.setText(_translate("MainWindow", "LED6:"))
        self.CBLed7.setText(_translate("MainWindow", "LED7"))
        self.CBLed8.setText(_translate("MainWindow", "LED8"))
        self.CBLed4.setText(_translate("MainWindow", "LED4"))
        self.LblStructure.setText(_translate("MainWindow", "Effect List:"))
        self.BtnAddSequence.setText(_translate("MainWindow", "Add Sequencer"))
        self.LBLLed4_2.setText(_translate("MainWindow", "LED4:"))
        self.LBLLed5_2.setText(_translate("MainWindow", "LED5:"))
        self.LBLLed1_2.setText(_translate("MainWindow", "LED1:"))
        self.LblCount.setText(_translate("MainWindow", "Count:"))
        self.ComboCount.setItemText(0, _translate("MainWindow", "forever"))
        self.ComboCount.setItemText(1, _translate("MainWindow", "1"))
        self.ComboCount.setItemText(2, _translate("MainWindow", "2"))
        self.ComboCount.setItemText(3, _translate("MainWindow", "3"))
        self.ComboCount.setItemText(4, _translate("MainWindow", "4"))
        self.ComboCount.setItemText(5, _translate("MainWindow", "5"))
        self.ComboCount.setItemText(6, _translate("MainWindow", "6"))
        self.ComboCount.setItemText(7, _translate("MainWindow", "7"))
        self.ComboCount.setItemText(8, _translate("MainWindow", "8"))
        self.ComboCount.setItemText(9, _translate("MainWindow", "9"))
        self.ComboCount.setItemText(10, _translate("MainWindow", "10"))
        self.LblLed.setText(_translate("MainWindow", "LED:"))
        self.LblName.setText(_translate("MainWindow", "Effect name:"))
        self.LblLeds.setText(_translate("MainWindow", "Leds for Sequencer:"))
        self.CBLed1.setText(_translate("MainWindow", "LED1"))
        self.LblRepeat.setText(_translate("MainWindow", "Repeat:"))
        self.CBLed5.setText(_translate("MainWindow", "LED5"))
        self.BtnDelete.setText(_translate("MainWindow", "Delete"))
        self.CBLed2.setText(_translate("MainWindow", "LED2"))
        self.CBLed6.setText(_translate("MainWindow", "LED6"))
        self.LblBrigtness.setText(_translate("MainWindow", "Led Brightness:"))
        self.LBLLed_2.setText(_translate("MainWindow", "LED:"))
        self.LBLLed3_2.setText(_translate("MainWindow", "LED3:"))
        self.CBLedsAll.setText(_translate("MainWindow", "Check All"))
        self.LblList.setText(_translate("MainWindow", "Effects Structure:"))
        self.LBLBrightness2.setText(_translate("MainWindow", "Led Brightness:"))
        self.LBLLed8_2.setText(_translate("MainWindow", "LED8:"))
        self.CBLed3.setText(_translate("MainWindow", "LED3"))
        self.BtnAddStep.setText(_translate("MainWindow", "Add Step"))
        self.LblWait.setText(_translate("MainWindow", "Wait:"))
        self.LblSmooth.setText(_translate("MainWindow", "Smooth:"))
        self.LBLName.setText(_translate("MainWindow", "Name:"))
        self.LblStatus.setText(_translate("MainWindow", "Check status here:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabAuxLEDs), _translate("MainWindow", "AuxLeds"))
        self.LblGeneral.setText(_translate("MainWindow", "General Settings"))
        self.LblMotion.setText(_translate("MainWindow", "Motion Settings"))
        self.GBSpin.setTitle(_translate("MainWindow", "Spin"))
        self.LBLSpinCounter.setText(_translate("MainWindow", "Counter:"))
        self.LblSpinCircle.setText(_translate("MainWindow", "Circle:"))
        self.LBLSpinEnabled.setText(_translate("MainWindow", "Enabled:"))
        self.LblSpinW.setText(_translate("MainWindow", "Spin Start W:"))
        self.LblSpinWLow.setText(_translate("MainWindow", "WLow:"))
        self.GBSwing.setTitle(_translate("MainWindow", "Swing"))
        self.LblSwingWPercent.setText(_translate("MainWindow", "WPercent:"))
        self.LblSwingCircle.setText(_translate("MainWindow", "Circle:"))
        self.LblSwingHighW.setText(_translate("MainWindow", "High W Threshold:"))
        self.LblCircleW.setText(_translate("MainWindow", "Circle W Threshold:"))
        self.GBStab.setTitle(_translate("MainWindow", "Stab"))
        self.LblStabHighA.setText(_translate("MainWindow", "HighA:"))
        self.LblStabLowW.setText(_translate("MainWindow", "LowW:"))
        self.LblStabHitLevel.setText(_translate("MainWindow", "HitLevel:"))
        self.LblSpinLength.setText(_translate("MainWindow", "Length, ms:"))
        self.LblEnabled.setText(_translate("MainWindow", "Enabled:"))
        self.LblStabPercent.setText(_translate("MainWindow", "Percent:"))
        self.GBCommonBlade.setTitle(_translate("MainWindow", "Blade Settings"))
        self.LBLBlade2.setText(_translate("MainWindow", "Blade2:"))
        self.LblBandNumber.setText(_translate("MainWindow", "BandNumber:"))
        self.LBLBlade2Enabled.setText(_translate("MainWindow", "Enabled:"))
        self.LblBandNumber_2.setText(_translate("MainWindow", "BandNumber:"))
        self.LblPixPerBand_2.setText(_translate("MainWindow", "PixPerBand:"))
        self.LblPixPerBand.setText(_translate("MainWindow", "PixPerBand:"))
        self.LBLBlade1.setText(_translate("MainWindow", "Blade1:"))
        self.GBScrew.setTitle(_translate("MainWindow", "Screw"))
        self.LblScrewEnabled.setText(_translate("MainWindow", "Enabled:"))
        self.LbScrewHighW.setText(_translate("MainWindow", "HighW:"))
        self.LblScrewLowW.setText(_translate("MainWindow", "LowW:"))
        self.GBCommonDeadTime.setTitle(_translate("MainWindow", "DeadTime Settings"))
        self.LblAfterPowerOn.setText(_translate("MainWindow", "AfterPowerOn, ms:"))
        self.LblAfterBlaster.setText(_translate("MainWindow", "AfterBlaster, ms:"))
        self.LblAfterClash.setText(_translate("MainWindow", "AfterClash, ms:"))
        self.GBCommonVolume.setTitle(_translate("MainWindow", "Volume Settings"))
        self.LblCoarceLow.setText(_translate("MainWindow", "CoarseLow, %:"))
        self.LblCommon.setText(_translate("MainWindow", "Common, %:"))
        self.LblCOarseMid.setText(_translate("MainWindow", "CoarseMid, %:"))
        self.LblCoarseHigh.setText(_translate("MainWindow", "CoarseHigh, %:"))
        self.GBCommonSettings.setTitle(_translate("MainWindow", "Other Settings:"))
        self.LblPowerOffTimeout.setText(_translate("MainWindow", "PowerOffTimeout, ms:"))
        self.LblClashFlashDuration.setText(_translate("MainWindow", "ClashFlasDuration, ms:"))
        self.BtnSave.setText(_translate("MainWindow", "Save"))
        self.GBClash.setTitle(_translate("MainWindow", "Clash"))
        self.LblClashHitLevel.setText(_translate("MainWindow", "HitLevel:"))
        self.LblClashLength.setText(_translate("MainWindow", "Length, ms:"))
        self.LblClashHighA.setText(_translate("MainWindow", "HighA:"))
        self.LblClashLowW.setText(_translate("MainWindow", "LowW:"))
        self.BtnDefault.setText(_translate("MainWindow", "Back to default"))
        self.LblCommonStatus.setText(_translate("MainWindow", "Check Status:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabCommon), _translate("MainWindow", "Common"))
        self.LblProfile.setText(_translate("MainWindow", "Select Profile:"))
        self.LblProfileStatus.setText(_translate("MainWindow", "Check Status:"))
        self.BtnProfile.setText(_translate("MainWindow", "Add Profile"))
        self.GBAuxLeds.setTitle(_translate("MainWindow", "Select AuxLeds Effects for PowerOn Effect"))
        self.label.setText(_translate("MainWindow", "Already added:"))
        self.BtnAuxDelete.setText(_translate("MainWindow", "Delete"))
        self.BtnCReateAux.setText(_translate("MainWindow", "Add effect to PowerOn"))
        self.LblCreateAux.setText(_translate("MainWindow", "Or create custom:"))
        self.LblAddAux.setText(_translate("MainWindow", "Add existing:"))
        self.LblProfile_2.setText(_translate("MainWindow", "Profile name:"))
        self.BtnDeleteProfile.setText(_translate("MainWindow", "Delete Profile"))
        self.CBIndicate.setText(_translate("MainWindow", "Indicate Blaster, Clash, Lockup"))
        self.CBBlade.setItemText(0, _translate("MainWindow", "Current Blade: Blade1"))
        self.CBBlade.setItemText(1, _translate("MainWindow", "Current Blade: Blade2"))
        self.LblDelayBeforeOn.setText(_translate("MainWindow", "DelayBeforeOn:"))
        self.TabEffects.setTabText(self.TabEffects.indexOf(self.TabAfterWake), _translate("MainWindow", "AfterWake"))
        self.LBLBladeSpeed.setText(_translate("MainWindow", "Blade Speed: "))
        self.TabEffects.setTabText(self.TabEffects.indexOf(self.TabPowerOn), _translate("MainWindow", "PowerOn"))
        self.LblWorkingColor.setText(_translate("MainWindow", "Color:"))
        self.BtnWorkingColor.setText(_translate("MainWindow", "Select Color"))
        self.CBFlickering.setText(_translate("MainWindow", "Always Flickering"))
        self.CBFlaming.setText(_translate("MainWindow", "Flaming"))
        self.TabEffects.setTabText(self.TabEffects.indexOf(self.TabWorkingMode), _translate("MainWindow", "Working"))
        self.LblPowerOnSpeed.setText(_translate("MainWindow", "Blade Speed:"))
        self.CBMoveForward.setText(_translate("MainWindow", "Move Forward"))
        self.TabEffects.setTabText(self.TabEffects.indexOf(self.TabPowerOff), _translate("MainWindow", "PowerOff"))
        self.LblFlamingDelayMin.setText(_translate("MainWindow", "Min:"))
        self.LblFlamingDelayMax.setText(_translate("MainWindow", "Max:"))
        self.LblFlamingDelay.setText(_translate("MainWindow", "Delay, ms:"))
        self.BtnAddColor.setText(_translate("MainWindow", "AddColor"))
        self.BtnDeleteColor.setText(_translate("MainWindow", "Delete Color"))
        self.LblFlamingColors.setText(_translate("MainWindow", "Colors:"))
        self.LblFlamingSpeedMax.setText(_translate("MainWindow", "Max:"))
        self.LblFlamigSize.setText(_translate("MainWindow", "Size:"))
        self.LblFlamingSizeMax.setText(_translate("MainWindow", "Max:"))
        self.LblFlamingSpeed.setText(_translate("MainWindow", "Speed:"))
        self.LblFlamingSizeMin.setText(_translate("MainWindow", "Min:"))
        self.LblFlamingSpeedMin.setText(_translate("MainWindow", "Min:"))
        self.CBFlamingAlwaysOn.setText(_translate("MainWindow", "AlwaysOn"))
        self.TabEffects.setTabText(self.TabEffects.indexOf(self.TabFlaming), _translate("MainWindow", "Flaming"))
        self.LblFlickeringBrMin.setText(_translate("MainWindow", "Min:"))
        self.LblFlickeringBrMax.setText(_translate("MainWindow", "Max:"))
        self.LblFlickeringSizeMax.setText(_translate("MainWindow", "Max:"))
        self.LblFlickeringSizeMin.setText(_translate("MainWindow", "Min:"))
        self.LblFlickeringBrigtness.setText(_translate("MainWindow", "Brightness:"))
        self.LblFlickeringTime.setText(_translate("MainWindow", "Time, ms:"))
        self.CBFlickeringAlwaysOn.setText(_translate("MainWindow", "AlwaysOn"))
        self.TabEffects.setTabText(self.TabEffects.indexOf(self.TabFlickering), _translate("MainWindow", "Flickering"))
        self.LBBlasterColor.setText(_translate("MainWindow", "Color:"))
        self.BtnBlasterColor.setText(_translate("MainWindow", "Select Color"))
        self.LblBlasterDuration.setText(_translate("MainWindow", "Duration, ms:"))
        self.LblSizePixDuration.setText(_translate("MainWindow", "SizePix:"))
        self.TabEffects.setTabText(self.TabEffects.indexOf(self.TabBlaster), _translate("MainWindow", "Blaster"))
        self.LblClashSizePix.setText(_translate("MainWindow", "SizePix:"))
        self.BtnClashColor.setText(_translate("MainWindow", "Select Color"))
        self.LblClashDuration.setText(_translate("MainWindow", "Duration, ms:"))
        self.LblClashCOlor.setText(_translate("MainWindow", "Color:"))
        self.TabEffects.setTabText(self.TabEffects.indexOf(self.TabClash), _translate("MainWindow", "Clash"))
        self.LblStabColor.setText(_translate("MainWindow", "Color:"))
        self.LblStabDuration.setText(_translate("MainWindow", "Duration, ms:"))
        self.BtnStabColor.setText(_translate("MainWindow", "Select Color"))
        self.LblStabSizePix.setText(_translate("MainWindow", "SizePix:"))
        self.TabEffects.setTabText(self.TabEffects.indexOf(self.TabStab), _translate("MainWindow", "Stab"))
        self.TxtLockupFlashesColor.setText(_translate("MainWindow", "255, 0, 0"))
        self.BtnLockupFlickerColor.setText(_translate("MainWindow", "Select Color"))
        self.LblLockupTimeMin.setText(_translate("MainWindow", "Min:"))
        self.LblLockupTime.setText(_translate("MainWindow", "Time:"))
        self.LblLockupFlickerColor.setText(_translate("MainWindow", "Color:"))
        self.LblLockupTimeMax.setText(_translate("MainWindow", "Max:"))
        self.LblLockupPeriod.setText(_translate("MainWindow", "Period:"))
        self.TxtLockupFlickerColor.setText(_translate("MainWindow", "255, 0, 0"))
        self.BtnLockupFlashesColor.setText(_translate("MainWindow", "Select Color"))
        self.LblLockupDuration.setText(_translate("MainWindow", "Duration, ms"))
        self.LblLockupSizepix.setText(_translate("MainWindow", "Sizepix:"))
        self.LblLockupPeriodMin.setText(_translate("MainWindow", "Min:"))
        self.LblLockcupBrightnessMax.setText(_translate("MainWindow", "Max:"))
        self.LblLockupFlicker.setText(_translate("MainWindow", "Flicker:"))
        self.LblLockupFlashes.setText(_translate("MainWindow", "Flashes:"))
        self.LblLockupBrightness.setText(_translate("MainWindow", "Brightness:"))
        self.LblLockupFlashesColor.setText(_translate("MainWindow", "Color:"))
        self.LblLockupBrightnessMin.setText(_translate("MainWindow", "Min:"))
        self.LblLockupPeriodMax.setText(_translate("MainWindow", "Max:"))
        self.TabEffects.setTabText(self.TabEffects.indexOf(self.TabLockup), _translate("MainWindow", "Lockup"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabProfile), _translate("MainWindow", "Profile"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAuxLeds_Editor_Help.setText(_translate("MainWindow", "AuxLeds Editor Help..."))
        self.actionAbout.setText(_translate("MainWindow", "About"))

