# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(978, 535)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.HSliderBrightness2 = QtWidgets.QSlider(self.centralwidget)
        self.HSliderBrightness2.setEnabled(False)
        self.HSliderBrightness2.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness2.setObjectName("HSliderBrightness2")
        self.gridLayout.addWidget(self.HSliderBrightness2, 9, 2, 1, 1)
        self.BtnEdit = QtWidgets.QPushButton(self.centralwidget)
        self.BtnEdit.setEnabled(False)
        self.BtnEdit.setObjectName("BtnEdit")
        self.gridLayout.addWidget(self.BtnEdit, 14, 7, 1, 1)
        self.TrStructure = QtWidgets.QTreeWidget(self.centralwidget)
        self.TrStructure.setObjectName("TrStructure")
        self.TrStructure.headerItem().setText(0, "1")
        self.TrStructure.header().setVisible(False)
        self.gridLayout.addWidget(self.TrStructure, 1, 1, 1, 8)
        self.BtnCreate = QtWidgets.QPushButton(self.centralwidget)
        self.BtnCreate.setEnabled(False)
        self.BtnCreate.setObjectName("BtnCreate")
        self.gridLayout.addWidget(self.BtnCreate, 2, 8, 1, 1)
        self.LBLLed2_2 = QtWidgets.QLabel(self.centralwidget)
        self.LBLLed2_2.setEnabled(False)
        self.LBLLed2_2.setObjectName("LBLLed2_2")
        self.gridLayout.addWidget(self.LBLLed2_2, 9, 1, 1, 1)
        self.LstEffects = QtWidgets.QListWidget(self.centralwidget)
        self.LstEffects.setObjectName("LstEffects")
        self.gridLayout.addWidget(self.LstEffects, 1, 0, 1, 1)
        self.LBLLed7_2 = QtWidgets.QLabel(self.centralwidget)
        self.LBLLed7_2.setEnabled(False)
        self.LBLLed7_2.setObjectName("LBLLed7_2")
        self.gridLayout.addWidget(self.LBLLed7_2, 11, 3, 1, 1)
        self.BtnRepeat = QtWidgets.QPushButton(self.centralwidget)
        self.BtnRepeat.setEnabled(False)
        self.BtnRepeat.setObjectName("BtnRepeat")
        self.gridLayout.addWidget(self.BtnRepeat, 12, 8, 1, 1)
        self.LBLLed6_2 = QtWidgets.QLabel(self.centralwidget)
        self.LBLLed6_2.setEnabled(False)
        self.LBLLed6_2.setObjectName("LBLLed6_2")
        self.gridLayout.addWidget(self.LBLLed6_2, 12, 1, 1, 1)
        self.CBLed7 = QtWidgets.QCheckBox(self.centralwidget)
        self.CBLed7.setEnabled(False)
        self.CBLed7.setObjectName("CBLed7")
        self.gridLayout.addWidget(self.CBLed7, 4, 7, 1, 1)
        self.CBLed8 = QtWidgets.QCheckBox(self.centralwidget)
        self.CBLed8.setEnabled(False)
        self.CBLed8.setObjectName("CBLed8")
        self.gridLayout.addWidget(self.CBLed8, 5, 7, 1, 1)
        self.CBLed4 = QtWidgets.QCheckBox(self.centralwidget)
        self.CBLed4.setEnabled(False)
        self.CBLed4.setObjectName("CBLed4")
        self.gridLayout.addWidget(self.CBLed4, 5, 3, 1, 2)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 10, 6, 1, 2)
        self.ComboRepeat = QtWidgets.QComboBox(self.centralwidget)
        self.ComboRepeat.setEnabled(False)
        self.ComboRepeat.setObjectName("ComboRepeat")
        self.gridLayout.addWidget(self.ComboRepeat, 12, 6, 1, 1)
        self.LblStructure = QtWidgets.QLabel(self.centralwidget)
        self.LblStructure.setObjectName("LblStructure")
        self.gridLayout.addWidget(self.LblStructure, 0, 0, 1, 1)
        self.BtnAddSequence = QtWidgets.QPushButton(self.centralwidget)
        self.BtnAddSequence.setEnabled(False)
        self.BtnAddSequence.setObjectName("BtnAddSequence")
        self.gridLayout.addWidget(self.BtnAddSequence, 5, 8, 1, 1)
        self.LBLLed4_2 = QtWidgets.QLabel(self.centralwidget)
        self.LBLLed4_2.setEnabled(False)
        self.LBLLed4_2.setObjectName("LBLLed4_2")
        self.gridLayout.addWidget(self.LBLLed4_2, 9, 3, 1, 1)
        self.HSliderBrightness4 = QtWidgets.QSlider(self.centralwidget)
        self.HSliderBrightness4.setEnabled(False)
        self.HSliderBrightness4.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness4.setObjectName("HSliderBrightness4")
        self.gridLayout.addWidget(self.HSliderBrightness4, 9, 4, 1, 1)
        self.LBLLed5_2 = QtWidgets.QLabel(self.centralwidget)
        self.LBLLed5_2.setEnabled(False)
        self.LBLLed5_2.setObjectName("LBLLed5_2")
        self.gridLayout.addWidget(self.LBLLed5_2, 11, 1, 1, 1)
        self.LBLLed1_2 = QtWidgets.QLabel(self.centralwidget)
        self.LBLLed1_2.setEnabled(False)
        self.LBLLed1_2.setObjectName("LBLLed1_2")
        self.gridLayout.addWidget(self.LBLLed1_2, 8, 1, 1, 1)
        self.HSliderBrightness1 = QtWidgets.QSlider(self.centralwidget)
        self.HSliderBrightness1.setEnabled(False)
        self.HSliderBrightness1.setMaximum(100)
        self.HSliderBrightness1.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness1.setObjectName("HSliderBrightness1")
        self.gridLayout.addWidget(self.HSliderBrightness1, 8, 2, 1, 1)
        self.HSliderBrightness8 = QtWidgets.QSlider(self.centralwidget)
        self.HSliderBrightness8.setEnabled(False)
        self.HSliderBrightness8.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness8.setObjectName("HSliderBrightness8")
        self.gridLayout.addWidget(self.HSliderBrightness8, 12, 4, 1, 1)
        self.HSliderBrightness5 = QtWidgets.QSlider(self.centralwidget)
        self.HSliderBrightness5.setEnabled(False)
        self.HSliderBrightness5.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness5.setObjectName("HSliderBrightness5")
        self.gridLayout.addWidget(self.HSliderBrightness5, 11, 2, 1, 1)
        self.LblCount = QtWidgets.QLabel(self.centralwidget)
        self.LblCount.setObjectName("LblCount")
        self.gridLayout.addWidget(self.LblCount, 11, 7, 1, 1)
        self.ComboCount = QtWidgets.QComboBox(self.centralwidget)
        self.ComboCount.setEnabled(False)
        self.ComboCount.setObjectName("ComboCount")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.ComboCount.addItem("")
        self.gridLayout.addWidget(self.ComboCount, 12, 7, 1, 1)
        self.LblLed = QtWidgets.QLabel(self.centralwidget)
        self.LblLed.setObjectName("LblLed")
        self.gridLayout.addWidget(self.LblLed, 7, 1, 1, 1)
        self.HSliderBrightness6 = QtWidgets.QSlider(self.centralwidget)
        self.HSliderBrightness6.setEnabled(False)
        self.HSliderBrightness6.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness6.setObjectName("HSliderBrightness6")
        self.gridLayout.addWidget(self.HSliderBrightness6, 12, 2, 1, 1)
        self.LblName = QtWidgets.QLabel(self.centralwidget)
        self.LblName.setObjectName("LblName")
        self.gridLayout.addWidget(self.LblName, 2, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 1, 1, 8)
        self.LblLeds = QtWidgets.QLabel(self.centralwidget)
        self.LblLeds.setObjectName("LblLeds")
        self.gridLayout.addWidget(self.LblLeds, 4, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 6, 1, 1, 8)
        self.CBLed1 = QtWidgets.QCheckBox(self.centralwidget)
        self.CBLed1.setEnabled(False)
        self.CBLed1.setObjectName("CBLed1")
        self.gridLayout.addWidget(self.CBLed1, 4, 2, 1, 1)
        self.LblRepeat = QtWidgets.QLabel(self.centralwidget)
        self.LblRepeat.setObjectName("LblRepeat")
        self.gridLayout.addWidget(self.LblRepeat, 11, 6, 1, 1)
        self.CBLed5 = QtWidgets.QCheckBox(self.centralwidget)
        self.CBLed5.setEnabled(False)
        self.CBLed5.setObjectName("CBLed5")
        self.gridLayout.addWidget(self.CBLed5, 4, 6, 1, 1)
        self.BtnDelete = QtWidgets.QPushButton(self.centralwidget)
        self.BtnDelete.setEnabled(False)
        self.BtnDelete.setObjectName("BtnDelete")
        self.gridLayout.addWidget(self.BtnDelete, 14, 8, 1, 1)
        self.CBLed2 = QtWidgets.QCheckBox(self.centralwidget)
        self.CBLed2.setEnabled(False)
        self.CBLed2.setObjectName("CBLed2")
        self.gridLayout.addWidget(self.CBLed2, 5, 2, 1, 1)
        self.CBLed6 = QtWidgets.QCheckBox(self.centralwidget)
        self.CBLed6.setEnabled(False)
        self.CBLed6.setObjectName("CBLed6")
        self.gridLayout.addWidget(self.CBLed6, 5, 6, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 11, 5, 2, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 13, 1, 1, 8)
        self.LblBrigtness = QtWidgets.QLabel(self.centralwidget)
        self.LblBrigtness.setObjectName("LblBrigtness")
        self.gridLayout.addWidget(self.LblBrigtness, 7, 2, 1, 1)
        self.LBLLed_2 = QtWidgets.QLabel(self.centralwidget)
        self.LBLLed_2.setObjectName("LBLLed_2")
        self.gridLayout.addWidget(self.LBLLed_2, 7, 3, 1, 1)
        self.LBLLed3_2 = QtWidgets.QLabel(self.centralwidget)
        self.LBLLed3_2.setEnabled(False)
        self.LBLLed3_2.setObjectName("LBLLed3_2")
        self.gridLayout.addWidget(self.LBLLed3_2, 8, 3, 1, 1)
        self.TxtName = QtWidgets.QLineEdit(self.centralwidget)
        self.TxtName.setObjectName("TxtName")
        self.gridLayout.addWidget(self.TxtName, 2, 2, 1, 6)
        self.CBLedsAll = QtWidgets.QCheckBox(self.centralwidget)
        self.CBLedsAll.setEnabled(False)
        self.CBLedsAll.setObjectName("CBLedsAll")
        self.gridLayout.addWidget(self.CBLedsAll, 5, 1, 1, 1)
        self.LblList = QtWidgets.QLabel(self.centralwidget)
        self.LblList.setObjectName("LblList")
        self.gridLayout.addWidget(self.LblList, 0, 1, 1, 1)
        self.HSliderBrightness3 = QtWidgets.QSlider(self.centralwidget)
        self.HSliderBrightness3.setEnabled(False)
        self.HSliderBrightness3.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness3.setObjectName("HSliderBrightness3")
        self.gridLayout.addWidget(self.HSliderBrightness3, 8, 4, 1, 1)
        self.LBLBrightness2 = QtWidgets.QLabel(self.centralwidget)
        self.LBLBrightness2.setObjectName("LBLBrightness2")
        self.gridLayout.addWidget(self.LBLBrightness2, 7, 4, 1, 1)
        self.HSliderBrightness7 = QtWidgets.QSlider(self.centralwidget)
        self.HSliderBrightness7.setEnabled(False)
        self.HSliderBrightness7.setOrientation(QtCore.Qt.Horizontal)
        self.HSliderBrightness7.setObjectName("HSliderBrightness7")
        self.gridLayout.addWidget(self.HSliderBrightness7, 11, 4, 1, 1)
        self.LBLLed8_2 = QtWidgets.QLabel(self.centralwidget)
        self.LBLLed8_2.setEnabled(False)
        self.LBLLed8_2.setObjectName("LBLLed8_2")
        self.gridLayout.addWidget(self.LBLLed8_2, 12, 3, 1, 1)
        self.CBLed3 = QtWidgets.QCheckBox(self.centralwidget)
        self.CBLed3.setEnabled(False)
        self.CBLed3.setObjectName("CBLed3")
        self.gridLayout.addWidget(self.CBLed3, 4, 3, 1, 2)
        self.SpinWait = QtWidgets.QSpinBox(self.centralwidget)
        self.SpinWait.setEnabled(False)
        self.SpinWait.setMaximum(1000)
        self.SpinWait.setObjectName("SpinWait")
        self.gridLayout.addWidget(self.SpinWait, 9, 6, 1, 1)
        self.SpinSmooth = QtWidgets.QSpinBox(self.centralwidget)
        self.SpinSmooth.setEnabled(False)
        self.SpinSmooth.setMaximum(100)
        self.SpinSmooth.setObjectName("SpinSmooth")
        self.gridLayout.addWidget(self.SpinSmooth, 9, 7, 1, 1)
        self.BtnAddStep = QtWidgets.QPushButton(self.centralwidget)
        self.BtnAddStep.setEnabled(False)
        self.BtnAddStep.setObjectName("BtnAddStep")
        self.gridLayout.addWidget(self.BtnAddStep, 9, 8, 1, 1)
        self.LblWait = QtWidgets.QLabel(self.centralwidget)
        self.LblWait.setObjectName("LblWait")
        self.gridLayout.addWidget(self.LblWait, 8, 6, 1, 1)
        self.LblSmooth = QtWidgets.QLabel(self.centralwidget)
        self.LblSmooth.setObjectName("LblSmooth")
        self.gridLayout.addWidget(self.LblSmooth, 8, 7, 1, 1)
        self.LBLName = QtWidgets.QLabel(self.centralwidget)
        self.LBLName.setObjectName("LBLName")
        self.gridLayout.addWidget(self.LBLName, 7, 6, 1, 1)
        self.TxtStepName = QtWidgets.QLineEdit(self.centralwidget)
        self.TxtStepName.setObjectName("TxtStepName")
        self.gridLayout.addWidget(self.TxtStepName, 7, 7, 1, 1)
        self.gridLayout.setColumnStretch(1, 10)
        self.gridLayout.setColumnStretch(2, 10)
        self.gridLayout.setColumnStretch(3, 5)
        self.gridLayout.setColumnStretch(4, 5)
        self.gridLayout.setColumnStretch(5, 10)
        self.gridLayout.setColumnStretch(6, 10)
        self.gridLayout.setRowStretch(1, 20)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 978, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAuxLeds_Editor_Help = QtWidgets.QAction(MainWindow)
        self.actionAuxLeds_Editor_Help.setObjectName("actionAuxLeds_Editor_Help")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAuxLeds_Editor_Help)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SettingsEditor"))
        self.BtnEdit.setText(_translate("MainWindow", "Edit"))
        self.BtnCreate.setText(_translate("MainWindow", "Create Effect"))
        self.LBLLed2_2.setText(_translate("MainWindow", "LED2:"))
        self.LBLLed7_2.setText(_translate("MainWindow", "LED7:"))
        self.BtnRepeat.setText(_translate("MainWindow", "AddRepeat"))
        self.LBLLed6_2.setText(_translate("MainWindow", "LED6:"))
        self.CBLed7.setText(_translate("MainWindow", "LED7"))
        self.CBLed8.setText(_translate("MainWindow", "LED8"))
        self.CBLed4.setText(_translate("MainWindow", "LED4"))
        self.LblStructure.setText(_translate("MainWindow", "Effect List:"))
        self.BtnAddSequence.setText(_translate("MainWindow", "Add Sequencer"))
        self.LBLLed4_2.setText(_translate("MainWindow", "LED4:"))
        self.LBLLed5_2.setText(_translate("MainWindow", "LED5:"))
        self.LBLLed1_2.setText(_translate("MainWindow", "LED1:"))
        self.LblCount.setText(_translate("MainWindow", "Count:"))
        self.ComboCount.setItemText(0, _translate("MainWindow", "forever"))
        self.ComboCount.setItemText(1, _translate("MainWindow", "1"))
        self.ComboCount.setItemText(2, _translate("MainWindow", "2"))
        self.ComboCount.setItemText(3, _translate("MainWindow", "3"))
        self.ComboCount.setItemText(4, _translate("MainWindow", "4"))
        self.ComboCount.setItemText(5, _translate("MainWindow", "5"))
        self.ComboCount.setItemText(6, _translate("MainWindow", "6"))
        self.ComboCount.setItemText(7, _translate("MainWindow", "7"))
        self.ComboCount.setItemText(8, _translate("MainWindow", "8"))
        self.ComboCount.setItemText(9, _translate("MainWindow", "9"))
        self.ComboCount.setItemText(10, _translate("MainWindow", "10"))
        self.LblLed.setText(_translate("MainWindow", "LED:"))
        self.LblName.setText(_translate("MainWindow", "Effect name:"))
        self.LblLeds.setText(_translate("MainWindow", "Leds for Sequencer:"))
        self.CBLed1.setText(_translate("MainWindow", "LED1"))
        self.LblRepeat.setText(_translate("MainWindow", "Repeat:"))
        self.CBLed5.setText(_translate("MainWindow", "LED5"))
        self.BtnDelete.setText(_translate("MainWindow", "Delete"))
        self.CBLed2.setText(_translate("MainWindow", "LED2"))
        self.CBLed6.setText(_translate("MainWindow", "LED6"))
        self.LblBrigtness.setText(_translate("MainWindow", "Led Brightness:"))
        self.LBLLed_2.setText(_translate("MainWindow", "LED:"))
        self.LBLLed3_2.setText(_translate("MainWindow", "LED3:"))
        self.CBLedsAll.setText(_translate("MainWindow", "Check All"))
        self.LblList.setText(_translate("MainWindow", "Effects Structure:"))
        self.LBLBrightness2.setText(_translate("MainWindow", "Led Brightness:"))
        self.LBLLed8_2.setText(_translate("MainWindow", "LED8:"))
        self.CBLed3.setText(_translate("MainWindow", "LED3"))
        self.BtnAddStep.setText(_translate("MainWindow", "Add Step"))
        self.LblWait.setText(_translate("MainWindow", "Wait:"))
        self.LblSmooth.setText(_translate("MainWindow", "Smooth:"))
        self.LBLName.setText(_translate("MainWindow", "Name:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAuxLeds_Editor_Help.setText(_translate("MainWindow", "AuxLeds Editor Help..."))
        self.actionAbout.setText(_translate("MainWindow", "About"))

