local_table = {               'Метка': {'en': 'Английский', 'ru': 'Русский', 'jp': 'Японский'},
               'Меню': {'en': '', 'ru': '', 'jp': ''},
               'New': {'en': 'New', 'ru': 'Создать', 'jp': '新規'},
               'Open': {'en': 'Open', 'ru': 'Открыть', 'jp': '開く'},
               'Open All': {'en': 'Open All', 'ru': 'Открыть все', 'jp': 'すべて開く'},
               'Save': {'en': 'Save', 'ru': 'Сохранить', 'jp': '保存'},
               'Save As': {'en': 'Save as', 'ru': 'Сохранить как', 'jp': '名前を付けて保存'},
               'Save All': {'en': 'Save all', 'ru': 'Сохранить все', 'jp': ''},
               'Exit': {'en': 'Exit', 'ru': 'Выйти', 'jp': '終了'},
               'File': {'en': 'File', 'ru': 'Файл', 'jp': 'ファイル'},
               'Help': {'en': 'Help', 'ru': 'Справка', 'jp': 'ヘルプ'},
               'AuxLeds Editor Help': {'en': 'AuxLeds Editor Help', 'ru': 'Справка по Auxleds', 'jp': 'アクセントLEDエディターヘルプ'},
               'Common Editor Help': {'en': 'Common Editor Help', 'ru': 'Справка по Common', 'jp': 'コモンエディターヘルプ'},
               'Profiles Editor Help': {'en': 'Profiles Editor Help', 'ru': 'Cправка по Profiles', 'jp': 'プロファイルエディターヘルプ'},
               'About': {'en': 'About', 'ru': 'О программе', 'jp': 'このソフトについて'},
               'AuxLED, Группы': {'en': '', 'ru': '', 'jp': ''},
               'LED Group List Label': {'en': 'AUXLEDs', 'ru': 'Дополнительные диоды', 'jp': 'アクセントLEDグループ'},
               'Auxiliary LED Group List (Accent Leds)': {'en': 'Auxiliary LED Group List (Accent Leds)', 'ru': 'Группы диодов', 'jp': 'アクセントLEDグループリスト'},
               'LED Group Name': {'en': 'LED Group Name', 'ru': 'Имя группы', 'jp': 'アクセントLEDグループ名'},
               'Add Group': {'en': 'Add Group', 'ru': 'Добавить группу', 'jp': 'グループを追加'},
               'Edit Group Name': {'en': 'Edit Group Name', 'ru': 'Обновить группу', 'jp': 'グループ更新'},
               'LEDs in the group': {'en': 'LEDs in the group', 'ru': 'Диоды в группе', 'jp': 'グループ内のLED'},
               'LED1': {'en': 'LED1', 'ru': 'Диод1', 'jp': 'LED1'},
               'LED2': {'en': 'LED2', 'ru': 'Диод2', 'jp': 'LED2'},
               'LED3': {'en': 'LED3', 'ru': 'Диод3', 'jp': 'LED3'},
               'LED4': {'en': 'LED4', 'ru': 'Диод4', 'jp': 'LED4'},
               'LED5': {'en': 'LED5', 'ru': 'Диод5', 'jp': 'LED5'},
               'LED6': {'en': 'LED6', 'ru': 'Диод6', 'jp': 'LED6'},
               'LED7': {'en': 'LED7', 'ru': 'Диод7', 'jp': 'LED7'},
               'LED8': {'en': 'LED8', 'ru': 'Диод8', 'jp': 'LED8'},
               'Delete Group': {'en': 'Delete Group', 'ru': 'Удалить группу', 'jp': 'グループを削除'},
               'Change LED': {'en': 'Change LED', 'ru': 'Заменить диод', 'jp': 'LEDを変更'},
               'with LED': {'en': 'with LED', 'ru': 'На диод', 'jp': 'LEDを使用'},
               'Change for all groups': {'en': 'Change for all groups', 'ru': 'Заменить диоды', 'jp': 'すべてのグループの変更'},
               'AuxLEDs, Секвенсеры': {'en': '', 'ru': '', 'jp': ''},
               'Sequencer List': {'en': 'Sequencer List', 'ru': 'Список циклов (секвенсеров)', 'jp': 'シーケンサーの一覧'},
               'Sequencer Name': {'en': 'Sequencer Name', 'ru': 'Имя цикла', 'jp': 'シーケンサー名'},
               'Add Sequencer': {'en': 'Add Sequencer', 'ru': 'Добавить новый\nцикл', 'jp': '新しいシーケンサーを追加'},
               'Or Copy Existing': {'en': 'Or Copy Existing', 'ru': 'или копировать', 'jp': 'または既存のも\nのをコピーする'},
               'Copy Sequencer': {'en': 'Copy Sequencer', 'ru': 'Копировать цикл', 'jp': 'シーケンサーをコピー'},
               'Delete Sequencer': {'en': 'Delete Sequencer', 'ru': 'Удалить цикл', 'jp': 'シーケンサーを削除'},
               'AuxLEDS, Steps': {'en': '', 'ru': '', 'jp': ''},
               'Step Creation': {'en': 'Step Creation', 'ru': 'Создать шаг', 'jp': 'ステップを作成'},
               'Edit Step': {'en': 'Edit Step', 'ru': 'Редактировать шаг', 'jp': ''},
               'Step Name': {'en': 'Step Name', 'ru': 'Имя шага', 'jp': 'ステップ名'},
               'New Name': {'en': 'New Name', 'ru': 'Новое имя шага', 'jp': ''},
               'Add Step': {'en': 'Add Step', 'ru': 'Добавить шаг', 'jp': 'ステップを追加'},
               'Delete Step': {'en': 'Delete Step', 'ru': 'Удалить шаг', 'jp': 'ステップを削除'},
               'LED': {'en': 'LED', 'ru': 'Диод', 'jp': 'LED'},
               'LED Brightness': {'en': 'LED Brightness', 'ru': 'Яркость диода', 'jp': 'LEDの明るさ'},
               'Copy Channel': {'en': 'Copy Channel', 'ru': 'Копировать канал', 'jp': 'チャンネルをコピー'},
               'None': {'en': 'None', 'ru': 'Нет', 'jp': '無し'},
               'CopyRed': {'en': 'CopyRed', 'ru': 'CopyRed', 'jp': 'Redをコピー'},
               'CopyGreen': {'en': 'CopyGreen', 'ru': 'CopyGreen', 'jp': 'Greenをコピー'},
               'CopyBlue': {'en': 'CopyBlue', 'ru': 'CopyBlue', 'jp': 'Blueをコピー'},
               'Wait': {'en': 'Wait', 'ru': 'Продолжительность', 'jp': '待つ'},
               'Smooth': {'en': 'Smooth', 'ru': 'Плавность', 'jp': '滑らかさ'},
               'Save Step': {'en': 'Save Step', 'ru': 'Сохранить шаг', 'jp': 'ステップを保存'},
               'Repeat Step': {'en': '', 'ru': '', 'jp': ''},
               'Repeat Step Creation': {'en': 'Repeat Step Creation', 'ru': 'Создать «повтор»/«зацикливание»', 'jp': 'ステップの作成を繰り返す'},
               'Start From': {'en': 'Start From', 'ru': 'Начать с шага', 'jp': 'ここから開始'},
               'Count': {'en': 'Count', 'ru': 'Повторять раз', 'jp': 'カウント'},
               'Forever': {'en': 'Forever', 'ru': 'Forever', 'jp': '繰り返し'},
               'Delete Repeat': {'en': 'Delete Repeat', 'ru': 'Удалить повтор', 'jp': '繰り返しを削除'},
               'Add Repeat': {'en': 'Add Repeat', 'ru': 'Добавить повтор', 'jp': '繰り返しを追加'},
               'Save Repeat': {'en': 'Save Repeat', 'ru': 'Сохранить повтор', 'jp': '繰り返しを保存'},
               'Open File Status': {'en': 'Open File Status', 'ru': 'Последнее действие с файлом', 'jp': 'ステータスファイルを開く'},
               'Служебные общие сообщения': {'en': '', 'ru': '', 'jp': ''},
               'try_open': {'en': 'Try to open', 'ru': 'Попытка открыть файл', 'jp': '開いています'},
               'open_warnings': {'en': 'successfully loaded', 'ru': 'успешно открыт', 'jp': '正常にロードされました'},
               'group_used': {'en': 'This group is used un sequencers, remove or edit them first', 'ru': 'Группа используется в циклах, необходимо сначала удалить или заменить их ', 'jp': 'このグループはシーケンサーなしで使用され、最初にそれらを削除または編集します'},
               'step_count_error': {'en': 'Wrong step count', 'ru': 'Неверное число повторов', 'jp': '有効なステップが見つかりません'},
               'sequencer_delete_error': {'en': 'This sequencer has steps, do you really want to delete it?', 'ru': 'У цикла имеются шаги, удалить весь цикл?', 'jp': 'このシーケンサーにはステップがあります。本当に削除しますか？'},
               'stepUsed_error': {'en': 'This step is used in repeat step, first delete repeat step', 'ru': 'Шаг использован в команде "повтор"/"зацикливание". сначала удалите этот шаг', 'jp': 'このステップは繰り返しステップで使用され、最初に繰り返しステップを削除します'},
               'open_file': {'en': 'Open File', 'ru': 'Открыть файл', 'jp': 'ファイルを開く'},
               'unsaved_warning': {'en': 'You have unsaved @@@  settings. Do you want to save?', 'ru': 'У вас есть несохраненный файл «@@@». Сохранить?', 'jp': '未保存の設定があります。 保存しますか？'},
               'yes': {'en': 'Yes', 'ru': 'Да ', 'jp': 'はい'},
               'no': {'en': 'No', 'ru': 'Нет', 'jp': 'いいえ'},
               'file_not_loaded': {'en': 'Could not load file', 'ru': 'Невозможно открыть файл', 'jp': 'ファイルを読み込めませんでした'},
               'no_file': {'en': 'No file in directory', 'ru': 'В папке нет файла', 'jp': 'ディレクトリにファイルがありません'},
               'Ошибки Auxleds': {'en': '', 'ru': '', 'jp': ''},
               'wrong_group_name': {'en': 'Wrong symbols in LED group name (only letters, digits and @@@ available)', 'ru': 'Неправильные символы в названии группы светодиодов (доступны только буквы, цифры и @@@)', 'jp': 'LEDグループ名に使用できない文字が含まれています（半角英数字および@@@のみ使用可能）'},
               'wrong_seq_name': {'en': 'Wrong symbols in Sequencer name (only letters, digits and @@@ available)', 'ru': 'Неправильные символы в имени циклов (доступны только буквы, цифры и @@@)', 'jp': 'シーケンサー名に使用できない文字が含まれています（半角英数字および@@@のみ使用可能）'},
               'seq_exists': {'en': 'This Sequencer name is already used', 'ru': 'Это имя цикла уже используется', 'jp': 'このシーケンサー名は既に使用されています'},
               'group_exists': {'en': 'This group name is already used', 'ru': 'Это имя группы уже используется', 'jp': 'このグループ名は既に使用されています'},
               'wrong_step_name': {'en': 'Wrong symbols in Step name (only letters, digits and @@@ available)', 'ru': 'Неправильные символы в названии шага (доступны только буквы, цифры и @@@)', 'jp': 'ステップ名に使用できない文字が含まれています（半角英数字および@@@のみ使用可能）'},
               'step_exists': {'en': 'This Step name is already used', 'ru': 'Это имя шага уже используется', 'jp': 'このステップ名は既に使用されています'},
               'leg_group_error': {'en': 'Error opening Led group from file. Error in:@@@', 'ru': 'Ошибка открытия группы светодиодов из файла. Ошибка в: @@@', 'jp': 'ファイルからLEDグループを開くときにエラーが発生しました。 エラー：@@@'},
               'empty_led_group': {'en': 'No Leds in Group', 'ru': 'Нет светодиодов в группе', 'jp': 'グループにLEDがありません'},
               'seq_error': {'en': 'Error in Sequencer description. Error in:@@@', 'ru': 'Ошибка в описании цикла. Ошибка в: @@@', 'jp': 'シーケンサーの説明に誤りがあります。 エラー：@@@'},
               'step_error': {'en': 'Error in Step description. Error in:@@@', 'ru': 'Ошибка в описании шага. Ошибка в: @@@', 'jp': 'ステップの説明に誤りがあります。 エラー：@@@'},
               'no_group': {'en': 'Group @@@ not found', 'ru': 'Группа @@@ не найдена', 'jp': 'グループ@@@が見つかりません'},
               'empty_group': {'en': 'Group name must not be empty', 'ru': 'Имя группы не должно быть пустым', 'jp': 'グループ名がありません'},
               'no_led': {'en': 'Led@@@ not found', 'ru': 'Не найден диод @@@', 'jp': 'LED@@@が見つかりませんでした'},
               'таба Common': {'en': '', 'ru': '', 'jp': ''},
               'General Settings': {'en': 'General Settings', 'ru': 'Общие настройки', 'jp': '一般設定'},
               'Blade Settings': {'en': 'Blade Settings', 'ru': 'Настройки лезвия', 'jp': 'ブレード設定'},
               'Blade1': {'en': 'Blade1', 'ru': 'Основной клинок', 'jp': 'ブレード1'},
               'Blade2': {'en': 'Blade2', 'ru': 'Второй клинок/Боковые лезвия', 'jp': 'ブレード2'},
               'Blade2 Settings': {'en': 'Blade Settings', 'ru': 'Настройки лезвия', 'jp': 'ブレード設定'},
               'Enabled': {'en': 'Enabled', 'ru': 'Включено', 'jp': '有効'},
               'Volume Settings': {'en': 'Volume Settings', 'ru': 'Настройки громкости', 'jp': '音量設定'},
               'DeadTime Settings': {'en': 'DeadTime Settings', 'ru': 'Настройки задержек срабатывания', 'jp': '制限時間の設定'},
               'Other Settings': {'en': 'Other Settings', 'ru': 'Другие настройки', 'jp': 'その他の設定'},
               'Motion Settings': {'en': 'Motion Settings', 'ru': 'Настройки движения', 'jp': 'モーション設定'},
               'Swing': {'en': 'Swing', 'ru': 'Взмах', 'jp': 'スイング'},
               'Spin': {'en': 'Spin', 'ru': 'Круговые вращения', 'jp': 'スピン'},
               'Clash': {'en': 'Clash', 'ru': 'Удар', 'jp': 'クラッシュ'},
               'Stab': {'en': 'Stab', 'ru': 'Тычок', 'jp': '突き'},
               'Screw': {'en': 'Screw', 'ru': 'Вкручивание (Жест)', 'jp': '捻り'},
               'Reset to Default': {'en': 'Reset to Default', 'ru': 'Сбросить «по умолчанию»', 'jp': '設定をリセット'},
               'Color dialog': {'en': '', 'ru': '', 'jp': ''},
               'Метка выбранного цвера': {'en': 'Selected Color', 'ru': 'Цвет', 'jp': '色選択'},
               'Метка saturation': {'en': 'Saturation', 'ru': 'Насыщенность', 'jp': '飽和'},
               'таб Profiles': {'en': '', 'ru': '', 'jp': ''},
               'Select Profile': {'en': 'Select Profile', 'ru': 'Выберите профиль', 'jp': 'プロファイルを選択'},
               'Profile Name': {'en': 'Profile Name', 'ru': 'Имя профиля', 'jp': 'プロファイル名'},
               'Add Profile': {'en': 'Add Profile', 'ru': 'Добавить профиль', 'jp': 'プロファイルを追加'},
               'Rename Selected Profile': {'en': 'Rename Selected Profile', 'ru': 'Переименовать выбранный профиль', 'jp': '選択したプロファイルの名前を変更'},
               'Delete Profile': {'en': 'Delete Profile', 'ru': 'Удалить профиль', 'jp': 'プロファイルを削除'},
               'Move Down': {'en': 'Move Down', 'ru': 'Сдвинуть вниз', 'jp': '下に移動'},
               'Move Up': {'en': 'Move Up', 'ru': 'Сдвинуть вверх', 'jp': '上に移動'},
               'Shadowed data in not awailable for current Blade ': {'en': 'Shadowed data in not awailable for current Blade ', 'ru': 'Затемненные данные\nне доступны для данного клинка', 'jp': '現在のブレードに対して次の項目は選択できません'},
               'Current Blade': {'en': 'Current Blade', 'ru': 'Текущий клинок', 'jp': '現在のブレード'},
               'Blade': {'en': 'Blade', 'ru': 'Клинок', 'jp': 'ブレード'},
               'Indicate Blaster, Clash, Lockup': {'en': 'Indicate Blaster, Clash, Lockup', 'ru': 'Вкл. Бластер, Удар, Клинч', 'jp': 'ブラスター、クラッシュ、ロックアップの表示'},
               'DelayBeforeOn': {'en': 'DelayBeforeOn', 'ru': 'Задержка перед включением', 'jp': 'ブレードの遅延設定'},
               'AfterWake': {'en': 'AfterWake', 'ru': 'После пробуждения', 'jp': '起動後'},
               'PowerOn': {'en': 'PowerOn', 'ru': 'Включение', 'jp': '電源オン'},
               'WorkingMode': {'en': 'WorkingMode', 'ru': 'Рабочий режим', 'jp': '動作モード'},
               'PowerOff': {'en': 'PowerOff', 'ru': 'Выключение', 'jp': '電源オフ'},
               'Flaming': {'en': 'Flaming', 'ru': 'Пламенный меч', 'jp': 'ファイヤーエフェクト'},
               'Flickering': {'en': 'Flickering', 'ru': 'Мерцание', 'jp': 'ちらつき'},
               'Blaster': {'en': 'Blaster', 'ru': 'Бластер', 'jp': 'ブラスター'},
               'Lockup': {'en': 'Lockup', 'ru': 'Клинч', 'jp': 'ロックアップ'},
               'Blade Speed': {'en': 'Blade Speed', 'ru': 'Скорость лезвия', 'jp': '伸縮スピード'},
               'Always Flickering': {'en': 'Always Flickering', 'ru': 'Всегда мерцает', 'jp': '常にちらつき'},
               'Flaming': {'en': 'Flaming', 'ru': 'Пылающий меч', 'jp': 'ファイヤーエフェクト'},
               'Move Forward': {'en': 'Move Forward', 'ru': 'Выключение от рукоятки', 'jp': '前進する'},
               'Size': {'en': 'Size', 'ru': 'Размер', 'jp': 'サイズ'},
               'Speed': {'en': 'Speed', 'ru': 'Скорость', 'jp': '速度'},
               'Delay': {'en': 'Delay', 'ru': 'Задержка', 'jp': 'ディレイ'},
               'ms': {'en': 'ms', 'ru': 'мс', 'jp': 'ミリ秒'},
               's': {'en': 's', 'ru': 'с', 'jp': ''},
               'Colors': {'en': 'Colors', 'ru': 'Цвета', 'jp': '色'},
               'Color': {'en': 'Color', 'ru': 'Цвет', 'jp': '色'},
               'Brightness': {'en': 'Brightness', 'ru': 'Яркость', 'jp': ''},
               'Min': {'en': 'Min', 'ru': 'Мин', 'jp': '最小'},
               'Max': {'en': 'Max', 'ru': 'Макс', 'jp': '最大'},
               'Delete Color': {'en': 'Delete Color', 'ru': 'Удалить цвет', 'jp': '色を削除'},
               'Add Color': {'en': 'Add Color', 'ru': 'Добавить цвет', 'jp': '色を追加'},
               'Time': {'en': 'Time', 'ru': 'Время', 'jp': '時間'},
               '(only for Blade2, see Working Mode for Blade1)':
                                  {'en': ' (only for Blade2, see Working Mode for Blade1)',
                                   'ru': ' (только для Blade 2, см. «Рабочий режим» для Blade 1)',
                                   'jp': ' (ブレード2のみブレード1の動作モード設定を適用する)'},
               'Select Color': {'en': 'Select Color', 'ru': 'Выбрать цвет', 'jp': '色を選択'},
               'Duration': {'en': 'Duration', 'ru': 'Длительность', 'jp': '期間'},
               'SizePix': {'en': 'SizePix', 'ru': 'Размер вспышки', 'jp': 'ピクセルサイズ'},
               'Color Selected': {'en': 'Color Selected', 'ru': 'Выбранный цвет', 'jp': '選択された色'},
               'Flicker Color': {'en': 'Flicker Color', 'ru': 'Цвет мерцания', 'jp': 'フリッカーカラー'},
               'Flashes Color': {'en': 'Flashes Color', 'ru': 'Цвет вспышек', 'jp': '色が点滅'},
               'Period': {'en': 'Period', 'ru': 'Период', 'jp': '期間'},
               'блок выбора аукс эффектов': {'en': '', 'ru': '', 'jp': ''},
               'Select AUXLEDs Effects for @@@ Effect': {'en': 'Select AUXLEDs Effects for@@@ Effect', 'ru': 'Выберите AUXLEDs Effects для @@@ Effect', 'jp': '@@@エフェクトにアクセントLEDエフェクトを選択'},
               'Add Existing': {'en': 'Add Existing', 'ru': 'Добавить существующий', 'jp': '既存を追加'},
               'Already Added': {'en': 'Already added', 'ru': 'Уже добавлено', 'jp': '追加済み'},
               'Or Create Custom': {'en': 'Or Create Custom', 'ru': 'Создать кастом', 'jp': 'カスタム作成'},
               'Add Effect to @@@': {'en': 'Add Effect to @@@', 'ru': 'Добавить эффект к @@@', 'jp': '@@@に効果を追加'},
               'Delete': {'en': 'Delete', 'ru': 'Удалить', 'jp': ''},
               'Cообщения табы Profiles': {'en': '', 'ru': '', 'jp': ''},
               'delete_profile': {'en': 'Do you realy want to delete this profile?', 'ru': 'Вы действительно хотите удалить этот профиль?', 'jp': '本当にこのプロファイルを削除しますか？'},
               'effect_exists': {'en': 'Effect for this LED group already added', 'ru': 'Эффект для этой группы светодиодов уже добавлен', 'jp': 'このLEDグループに対する効果はすでに追加されています'},
               'effect_used': {'en': 'Effect does not exiss or is already used', 'ru': 'Эффект не существует или уже используется', 'jp': '効果が存在しないか、既に使用されています'},
               'wrong_profile_data': {'en': 'Wrong profile data format', 'ru': 'Неправильный формат данных профиля', 'jp': '間違ったプロファイルデータフォーマット'},
               'Stripes in Chain': {'en': 'Stripes in Chain', 'ru': 'Количество лент \nв цепочке', 'jp': 'ストリップの本数'},
               'LEDs in Stripe': {'en': 'LEDs in Stripe', 'ru': 'Количество\nсветодиодов\nв ленте', 'jp': 'ストリップのLED数'},
               'Start Flash From №': {'en': 'Start Flash From №', 'ru': 'Начать эффекты\nс диода №', 'jp': '開始フラッシュ番号'},
               'Common, %': {'en': 'Common, %', 'ru': 'Общий уровень, %', 'jp': '一般 ％'},
               'Low Level, %': {'en': 'Low Level, %', 'ru': 'Низкий уровень, %', 'jp': '低レベル％'},
               'High Level, %': {'en': 'High Level, %', 'ru': 'Высокий уровень, %', 'jp': '高いレベル ％'},
               'Mid Level, %': {'en': 'Mid Level, %', 'ru': 'Средний уровень, %', 'jp': '中間レベル％'},
               'After Power On': {'en': 'After Power On', 'ru': 'После включения', 'jp': '電源投入後'},
               'After Blaster': {'en': 'After Blaster', 'ru': 'После бластера', 'jp': 'ブラスター後'},
               'After Clash': {'en': 'After Clash', 'ru': 'После столкновения', 'jp': 'クラッシュ後'},
               'Deep Sleep\nTimeout': {'en': 'Deep Sleep\nTimeout', 'ru': 'Время перехода в сон', 'jp': 'ディープスリープまでの時間'},
               'Threshold of Start': {'en': 'Threshold of Start', 'ru': 'Мин сила взмаха', 'jp': '開始のしきい値'},
               'Sensitivity\nof Next Swing, %': {'en': 'Sensitivity\nof Next Swing, %', 'ru': 'Чувствительность\nвторого взмаха, %', 'jp': '次のスイングの感度％'},
               'Circle Length': {'en': 'Circle Length', 'ru': 'Длина круга', 'jp': 'サークル範囲、ミリ秒'},
               'Circle Speed': {'en': 'Circle Speed', 'ru': 'Скорость кругового\nвзмаха', 'jp': '円の速度'},
               'Min Semicircle \nBefore Start': {'en': 'Min Semicircle\nBefore Start', 'ru': 'Мин полукругов\nдо перехода', 'jp': '開始前の最小円'},
               'Min Start Speed': {'en': 'Min Start Speed', 'ru': 'Мин скорость входа', 'jp': '最小起動速度'},
               'Min Out Speed': {'en': 'Min Out Speed', 'ru': 'Скорость выхода', 'jp': '最小終了速度'},
               'Min Strength': {'en': 'Min Strength', 'ru': 'Минимальная\nсила', 'jp': '最小強度'},
               'HitLevel': {'en': 'HitLevel', 'ru': 'Искажения', 'jp': 'ヒットレベル'},
               'Min Angular \nVelocity': {'en': 'Min Angular \nVelocity', 'ru': 'Мин угловая\nскорость', 'jp': '最小角速度'},
               'Max Angular\nDisplacement': {'en': 'Max Angular\nDisplacement', 'ru': 'Макс угловое\nсмещение', 'jp': '最大角変位'},
               'Allowed Offset, %': {'en': 'Allowed Offset, %', 'ru': 'Позволеное\nсмещение %', 'jp': '許容オフセット％'},
               'Max Angular \nDisplacement': {'en': 'Max Angular \nDisplacement', 'ru': 'Макс угловое\nсмещение', 'jp': '最大角変位'},
               'Rotational\n Speed': {'en': 'Rotational\n Speed', 'ru': 'Cкорость\nвращения', 'jp': '回転速度'},
               'Blade settings': {'en': 'Blade settings', 'ru': 'Настройки лезвия', 'jp': 'ブレード設定'},
               'Volume settings': {'en': 'Volume settings', 'ru': 'Настройки громкости', 'jp': '音量設定'},
               'Deadtime settings': {'en': 'Deadtime settings', 'ru': 'Настройки задержки', 'jp': '制限時間の設定'},
               'Other settings': {'en': 'Other settings', 'ru': 'Настройки питания', 'jp': 'その他の設定'},
               'Motion settings': {'en': 'Motion settings', 'ru': 'Настройки движения', 'jp': 'モーション設定'},
               'swing': {'en': 'swing', 'ru': 'Взмах (swing)', 'jp': 'スイング'},
               'spin': {'en': 'spin', 'ru': 'Переход взмахов во вращения (spin)', 'jp': 'スピン'},
               'clash': {'en': 'clash', 'ru': 'Удар', 'jp': 'クラッシュ'},
               'stab': {'en': 'stab', 'ru': 'Тычок', 'jp': '突き'},
               'screw': {'en': 'screw', 'ru': 'Жест (Вкручивание)', 'jp': '捻り'},
               'Use Random Colors': {'en': 'Use Random Colors', 'ru': 'Разноцветный режим', 'jp': 'ランダムカラーを使用'},
               'Add Random Color': {'en': 'Add Random Color', 'ru': 'Добавить «разноцвет»', 'jp': 'ランダムカラーを追加'},
               'AuxLEDs':{'en': 'AuxLEDs', 'ru':	'Настройки дополнительных диодов', 'jp': ''},
               'Common'	: {'en': 'Common', 'ru': 'Общие настройки', 'jp': ""},
               'Profiles':{'en': 'Profiles', 'ru': 'Настройки профилей', 'jp': ''},
               'Always On': {'en': 'Always On', 'ru': 'Всегда вкл.', 'jp': ''},
               'Step': {'en': 'Step', 'ru': 'Шаг', 'jp': ''},
               'Repeat': {'en': 'Repeat', 'ru': 'Повтор', 'jp': ''},
               'Save File': {'en': {'Save File'}, 'ru': 'Сохранение', 'jp': ""},
               'success_save': {'en': 'successfully saved', 'ru': 'успешно сохранен', 'jp': ''},
               'no_seq_name': {'en':'Sequencer name is absent', 'ru': 'Отсутсвует имя секвенсера', 'jp': ''},
               'wrong_start': {'en': 'Wrong start step', 'ru': 'Неверное начало цикла', 'jp':""},
               'data_error': {'en': 'Wrong data', 'ru': 'Ошибках в данных', 'jp': ""},
               'data_error_in': {'en': 'Data error in', 'ru': 'Ошибках в ', 'jp': ""},
               'Error': {'en': 'Error', 'ru': 'Ошибка', 'jp':''}
}